/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated intrinsic target tests: `movmatrix` intrinsics.

use super::super::*;

#[test]
fn movmatrix_trans_b16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0305").unwrap();
    assert_eq!(target.id, "movmatrix_trans_b16");
    assert_eq!(target.abi_id, "i0305");
    assert_eq!(target.dialect_op, "nvvm.movmatrix_trans_b16");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(75)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert!(target.llvm.is_none());
}
