/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated conversion interfaces: `execution_control` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    execution_control::convert_counted_barrier, execution_control::convert_grid_dependency,
    execution_control::convert_setmaxnreg,
};
use dialect_nvvm::ops::{
    BarrierCtaArriveAlignedCountOp, BarrierCtaArriveCountOp, BarrierCtaSyncAlignedCountOp,
    BarrierCtaSyncCountOp, GridDependencyLaunchDependentsOp, GridDependencyWaitOp, SetMaxNRegDecOp,
    SetMaxNRegIncOp,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for BarrierCtaArriveCountOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_counted_barrier(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_barrier_cta_arrive_count",
            "barrier.arrive $0, $1;",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for BarrierCtaArriveAlignedCountOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_counted_barrier(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_barrier_cta_arrive_aligned_count",
            "bar.arrive $0, $1;",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for BarrierCtaSyncCountOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_counted_barrier(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_barrier_cta_sync_count",
            "barrier.sync $0, $1;",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for BarrierCtaSyncAlignedCountOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_counted_barrier(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_barrier_cta_sync_aligned_count",
            "bar.sync $0, $1;",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for GridDependencyLaunchDependentsOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_grid_dependency(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_griddepcontrol_launch_dependents",
            "griddepcontrol.launch_dependents;",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for GridDependencyWaitOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_grid_dependency(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_griddepcontrol_wait",
            "griddepcontrol.wait;",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for SetMaxNRegDecOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let register_count = self.register_count(ctx).ok_or_else(|| {
            pliron::input_error_noloc!("setmaxnreg register-count attribute is invalid")
        })?;
        convert_setmaxnreg(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            register_count,
            "llvm_nvvm_setmaxnreg_dec_sync_aligned_u32",
            "dec",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for SetMaxNRegIncOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let register_count = self.register_count(ctx).ok_or_else(|| {
            pliron::input_error_noloc!("setmaxnreg register-count attribute is invalid")
        })?;
        convert_setmaxnreg(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            register_count,
            "llvm_nvvm_setmaxnreg_inc_sync_aligned_u32",
            "inc",
        )
    }
}
