/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated conversion interfaces: `vote` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::warp::convert_vote;
use dialect_nvvm::ops::{VoteSyncAllOp, VoteSyncAnyOp, VoteSyncBallotOp, VoteSyncUniOp};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncAllOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_all_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncAnyOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_any_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncBallotOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_ballot_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncUniOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_uni_sync",
        )
    }
}
