/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated conversion interfaces: `warp_barrier` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::warp::convert_bar_warp_sync;
use dialect_nvvm::ops::BarWarpSyncOp;
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for BarWarpSyncOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_bar_warp_sync(ctx, rewriter, self.get_operation(), operands_info)
    }
}
