; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 26a9cc13399662102ce0928e8e467b4c33476c2d84a05a08197049cb1c6b6b16.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.barrier.cta.sync.aligned.count(i32, i32)

define void @probe_barrier_cta_sync_aligned_rr(i32 %barrier_id, i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.sync.aligned.count(i32 %barrier_id, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_sync_aligned_ri(i32 %barrier_id) #0 {
  call void @llvm.nvvm.barrier.cta.sync.aligned.count(i32 %barrier_id, i32 32)
  ret void
}

define void @probe_barrier_cta_sync_aligned_ir(i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.sync.aligned.count(i32 1, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_sync_aligned_ii() #0 {
  call void @llvm.nvvm.barrier.cta.sync.aligned.count(i32 1, i32 32)
  ret void
}

attributes #0 = { convergent }
