; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 9b5ce71ce97b9a58e53bc98541d3449020497dbf7b46b91c1da19faf5b68619f.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.barrier.cta.red.popc.aligned.all(i32, i1)

define i32 @probe_barrier_cta_red_popc_aligned_all_r(i32 %barrier_id, i1 %predicate) #0 {
  %result = call i32 @llvm.nvvm.barrier.cta.red.popc.aligned.all(i32 %barrier_id, i1 %predicate)
  ret i32 %result
}

define i32 @probe_barrier_cta_red_popc_aligned_all_i(i1 %predicate) #0 {
  %result = call i32 @llvm.nvvm.barrier.cta.red.popc.aligned.all(i32 1, i1 %predicate)
  ret i32 %result
}

attributes #0 = { convergent }
