; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 371981c8a54acd95e6bbb14a457135d657e6afd0701a143687dc0072ea85a103.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.barrier.cluster.arrive.relaxed.aligned() #0

define void @probe_barrier_cluster_arrive_relaxed_aligned() #0 {
  call void @llvm.nvvm.barrier.cluster.arrive.relaxed.aligned() #0
  ret void
}

attributes #0 = { convergent }
