; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 478f564b163dc9e806fded98a951c6e5a36e14d9f95fe5cb8d897ac914411697.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.clusterlaunchcontrol.query_cancel.get_first_ctaid.y(i128)

define i32 @probe_clc_query_get_first_ctaid_y(i64 %response_low, i64 %response_high) {
  %response_low_i128 = zext i64 %response_low to i128
  %response_high_i128 = zext i64 %response_high to i128
  %response_high_shifted = shl i128 %response_high_i128, 64
  %response = or i128 %response_low_i128, %response_high_shifted
  %raw_result = call i32 @llvm.nvvm.clusterlaunchcontrol.query_cancel.get_first_ctaid.y(i128 %response)
  ret i32 %raw_result
}
