; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 371981c8a54acd95e6bbb14a457135d657e6afd0701a143687dc0072ea85a103.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i64 @llvm.nvvm.read.ptx.sreg.clock64()

define i64 @probe_clock64_lib_nvvm() {
  %result = call i64 @llvm.nvvm.read.ptx.sreg.clock64()
  ret i64 %result
}
