; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: c800783457da7afbcc50edc3a1f4cb85872d3e8cf9b6e265678c179894849e94.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i64 @llvm.nvvm.read.ptx.sreg.clock64()

define i64 @probe_clock64_lib_nvvm() {
  %result = call i64 @llvm.nvvm.read.ptx.sreg.clock64()
  ret i64 %result
}
