; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 60ad95ed39ec7cd6efee4efc375830839afee2655c6d410cd82acff9ff683dfd.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.commit.group()

define void @probe_cp_async_bulk_commit_group() {
  call void @llvm.nvvm.cp.async.bulk.commit.group()
  ret void
}
