; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 91c449f0f24034cc5016145e0267208394a0863995da74ec41064fccdc87a82d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.wait.group(i32)

define void @probe_cp_async_bulk_wait_group() {
  call void @llvm.nvvm.cp.async.bulk.wait.group(i32 0)
  ret void
}
