; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: f18b8acf1083c89e407f69c9140a59c2e1eeaa67ba70732c395127e889ca4a55.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_cvt_rn_relu_f16x2_e5m2x2(i16 %packed) {
  %result = call i32 asm "cvt.rn.relu.f16x2.e5m2x2 $0, $1;", "=r,h"(i16 %packed)
  ret i32 %result
}
