; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f8d4a39a54342e69f671b11a10007bef86f5c3ba4d277be328a7599be68455a9.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.f2tf32.rna.satfinite(float)

define i32 @probe_cvt_rna_satfinite_tf32_f32(float %value) {
  %result = call i32 @llvm.nvvm.f2tf32.rna.satfinite(float %value)
  ret i32 %result
}
