; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 9b5ce71ce97b9a58e53bc98541d3449020497dbf7b46b91c1da19faf5b68619f.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i16 @llvm.nvvm.ff.to.e4m3x2.rn.relu(float, float)

define i16 @probe_cvt_rn_satfinite_relu_e4m3x2_f32(float %low, float %high) {
  %result = call i16 @llvm.nvvm.ff.to.e4m3x2.rn.relu(float %high, float %low)
  ret i16 %result
}
