; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 02a6a6b3415ab7468c40db4cf5becc52a6c53da5ef7d944933e9cfa5858b4397.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_cvt_rz_f16x2_f32(float %low, float %high) {
  %result = call i32 asm "cvt.rz.f16x2.f32 $0, $2, $1;", "=r,f,f"(float %low, float %high)
  ret i32 %result
}
