; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 60ad95ed39ec7cd6efee4efc375830839afee2655c6d410cd82acff9ff683dfd.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_cvt_rn_f16x2_e2m1x2(i16 %packed) {
  %result = call i32 asm "{ .reg .b8 e2m1x2_byte; cvt.u8.u16 e2m1x2_byte, $1; cvt.rn.f16x2.e2m1x2 $0, e2m1x2_byte; }", "=r,h"(i16 %packed)
  ret i32 %result
}
