; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: d02f79ec316847b8022ac9b30f7d5b46ca77248a8f988700d18ad2e149e250c6.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i16 @probe_cvt_rn_satfinite_e5m2x2_f16x2(i32 %packed) {
  %result = call i16 asm "cvt.rn.satfinite.e5m2x2.f16x2 $0, $1;", "=h,r"(i32 %packed)
  ret i16 %result
}
