; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 00f22882dd98c60edf9aee0ec3676773da14d6c49d77af1c664a083bed3c44cb.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_cvt_rz_f16x2_f32(float %low, float %high) {
  %result = call i32 asm "cvt.rz.f16x2.f32 $0, $2, $1;", "=r,f,f"(float %low, float %high)
  ret i32 %result
}
