; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: a6962ae6c56aec0716a291570b7ac8e02bd1e4052ee151affa72d372f17faf3a.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.fence.proxy.tensormap_generic.acquire.gpu(ptr, i32)

define void @probe_fence_proxy_tensormap_generic_acquire_gpu(ptr %tensor_map) {
  call void @llvm.nvvm.fence.proxy.tensormap_generic.acquire.gpu(ptr %tensor_map, i32 128)
  ret void
}
