; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: df42ef977b4d7fd56331250cf6fd608cca2c1a11ce873e85b1f1b62f8f987484.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define void @probe_fence_proxy_async_generic_acquire_shared_cluster_cluster() #0 {
  call void asm sideeffect "fence.proxy.async::generic.acquire.sync_restrict::shared::cluster.cluster;", "~{memory}"() #0
  ret void
}

attributes #0 = { convergent }
