; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f8d4a39a54342e69f671b11a10007bef86f5c3ba4d277be328a7599be68455a9.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare double @llvm.nvvm.fma.rm.d(double, double, double)

define double @probe_fma_rm_f64(double %arg0, double %arg1, double %arg2) {
  %result = call double @llvm.nvvm.fma.rm.d(double %arg0, double %arg1, double %arg2)
  ret double %result
}
