; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: d02f79ec316847b8022ac9b30f7d5b46ca77248a8f988700d18ad2e149e250c6.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i64 @probe_gridid_lib_nvvm() {
  %result = call i64 asm "mov.u64 $0, %gridid;", "=l"()
  ret i64 %result
}
