; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 02a6a6b3415ab7468c40db4cf5becc52a6c53da5ef7d944933e9cfa5858b4397.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.match.any.sync.i64(i32, i64)

define i32 @probe_match_any_i64_sync_rr(i32 %member_mask, i64 %value) {
  %result = call i32 @llvm.nvvm.match.any.sync.i64(i32 %member_mask, i64 %value)
  ret i32 %result
}
define i32 @probe_match_any_i64_sync_ri(i64 %value) {
  %result = call i32 @llvm.nvvm.match.any.sync.i64(i32 -1, i64 %value)
  ret i32 %result
}
define i32 @probe_match_any_i64_sync_ir(i32 %member_mask) {
  %result = call i32 @llvm.nvvm.match.any.sync.i64(i32 %member_mask, i64 7)
  ret i32 %result
}
define i32 @probe_match_any_i64_sync_ii() {
  %result = call i32 @llvm.nvvm.match.any.sync.i64(i32 -1, i64 7)
  ret i32 %result
}
