; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 43/0.1.0; intrinsic ABI: v1; catalog SHA-256: 8822fe86e253cf6aa3b0680d15d431e3935faf51b360df0e6751894e07efe36c.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_max_nan_bf16x2(i32 %a, i32 %b) {
  %result = call i32 asm "max.NaN.bf16x2 $0, $1, $2;", "=r,r,r"(i32 %a, i32 %b)
  ret i32 %result
}
