; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 91c449f0f24034cc5016145e0267208394a0863995da74ec41064fccdc87a82d.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i1 @probe_mbarrier_try_wait(ptr %barrier_generic, i64 %token) #0 {
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %result_i32 = call i32 asm sideeffect "{ .reg .pred %p0; mbarrier.try_wait.shared.b64 %p0, [$1], $2; selp.b32 $0, 1, 0, %p0; }", "=r,l,l,~{memory}"(ptr addrspace(3) %barrier, i64 %token) #0
  %result = trunc i32 %result_i32 to i1
  ret i1 %result
}

attributes #0 = { convergent }
