; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 040addf39f4c68fd7971f2eb8394767802ff35f008f1291b02312e85efb73fc8.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define void @probe_mbarrier_arrive_cluster(i64 %address) #0 {
  call void asm sideeffect "mbarrier.arrive.release.cluster.shared::cluster.b64 _, [$0];", "l,~{memory}"(i64 %address) #0
  ret void
}

attributes #0 = { convergent }
