; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 9b5ce71ce97b9a58e53bc98541d3449020497dbf7b46b91c1da19faf5b68619f.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i64 @probe_mbarrier_arrive_expect_tx(ptr %barrier_generic, i32 %bytes) #0 {
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %token = call i64 asm sideeffect "mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 $0, [$1], $2;", "=l,l,r,~{memory}"(ptr addrspace(3) %barrier, i32 %bytes) #0
  ret i64 %token
}

attributes #0 = { convergent }
