; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 388e2e9d77a7f596f3bbdae979059975d8866b309b03605521252eb88b41ded6.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define float @probe_min_ftz_xorsign_abs_f32(float %a, float %b) {
  %result = call float asm "min.ftz.xorsign.abs.f32 $0, $1, $2;", "=f,f,f"(float %a, float %b)
  ret float %result
}
