; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 43/0.1.0; intrinsic ABI: v1; catalog SHA-256: 159568d9d27d46865ccecf8df25cea62f9c11a233541b0495bd36790b6c986a7.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_min_ftz_nan_f16x2(i32 %a, i32 %b) {
  %result = call i32 asm "min.ftz.NaN.f16x2 $0, $1, $2;", "=r,r,r"(i32 %a, i32 %b)
  ret i32 %result
}
