; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 45/0.1.0; intrinsic ABI: v1; catalog SHA-256: d31d6eda28b5bd4fbabfebb3c7d3a3095328bcfb5ba661782373491253ae9eb2.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_neg_bf16x2(i32 %arg0) {
  %result = call i32 asm "neg.bf16x2 $0, $1;", "=r,r"(i32 %arg0)
  ret i32 %result
}
