; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 26a9cc13399662102ce0928e8e467b4c33476c2d84a05a08197049cb1c6b6b16.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.setmaxnreg.dec.sync.aligned.u32(i32)

define void @probe_setmaxnreg_dec() #0 {
  call void @llvm.nvvm.setmaxnreg.dec.sync.aligned.u32(i32 64)
  ret void
}

attributes #0 = { convergent }
