; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 02a6a6b3415ab7468c40db4cf5becc52a6c53da5ef7d944933e9cfa5858b4397.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.shfl.sync.bfly.i32(i32, i32, i32, i32)

define i32 @probe_shuffle_xor_sync_rr(i32 %member_mask, i32 %value, i32 %lane) {
  %result = call i32 @llvm.nvvm.shfl.sync.bfly.i32(i32 %member_mask, i32 %value, i32 %lane, i32 31)
  ret i32 %result
}
define i32 @probe_shuffle_xor_sync_ri(i32 %value, i32 %lane) {
  %result = call i32 @llvm.nvvm.shfl.sync.bfly.i32(i32 -1, i32 %value, i32 %lane, i32 31)
  ret i32 %result
}
define i32 @probe_shuffle_xor_sync_ir(i32 %member_mask, i32 %value) {
  %result = call i32 @llvm.nvvm.shfl.sync.bfly.i32(i32 %member_mask, i32 %value, i32 1, i32 31)
  ret i32 %result
}
define i32 @probe_shuffle_xor_sync_ii(i32 %value) {
  %result = call i32 @llvm.nvvm.shfl.sync.bfly.i32(i32 -1, i32 %value, i32 1, i32 31)
  ret i32 %result
}
