; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 478f564b163dc9e806fded98a951c6e5a36e14d9f95fe5cb8d897ac914411697.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i64 @probe_shuffle_xor_u64_sync(i32 %member_mask, i64 %value, i32 %lane) #0 {
  %result = call i64 asm sideeffect "{ .reg .b32 lo; .reg .b32 hi; mov.b64 {lo, hi}, $1; shfl.sync.bfly.b32 lo, lo, $2, 31, $3; shfl.sync.bfly.b32 hi, hi, $2, 31, $3; mov.b64 $0, {lo, hi}; }", "=l,l,r,r"(i64 %value, i32 %lane, i32 %member_mask) #0
  ret i64 %result
}

attributes #0 = { convergent }
