; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 60ad95ed39ec7cd6efee4efc375830839afee2655c6d410cd82acff9ff683dfd.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare double @llvm.nvvm.sqrt.rz.d(double)

define double @probe_sqrt_rz_f64(double %arg0) {
  %result = call double @llvm.nvvm.sqrt.rz.d(double %arg0)
  ret double %result
}
