; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 040addf39f4c68fd7971f2eb8394767802ff35f008f1291b02312e85efb73fc8.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.bar.warp.sync(i32)

define void @probe_sync_mask(i32 %member_mask) {
  call void @llvm.nvvm.bar.warp.sync(i32 %member_mask)
  ret void
}
define void @probe_sync_mask_immediate() {
  call void @llvm.nvvm.bar.warp.sync(i32 -1)
  ret void
}
