; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 7e2b5911535b5c724e4e7d1dd7a2bc70c65b16b2e72311b29e41fd35339f1f5f.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.cp.4x256b.cg1; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_cp_4x256b(i32 %tmem, i64 %desc) #0 {
  call void asm sideeffect "tcgen05.cp.cta_group::1.4x256b [$0], $1;", "r,l,~{memory}"(i32 %tmem, i64 %desc) #0
  ret void
}

attributes #0 = { convergent }
