; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: a6962ae6c56aec0716a291570b7ac8e02bd1e4052ee151affa72d372f17faf3a.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.32x32b.x4; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_32x32b_x4_unpack16(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.32x32b.x4.unpack::16b.b32 [$0], {$1,$2,$3,$4};", "r,r,r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3) #0
  ret void
}

attributes #0 = { convergent }
