; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 9b5ce71ce97b9a58e53bc98541d3449020497dbf7b46b91c1da19faf5b68619f.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.16x128b.x1; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_16x128b_x1_raw(i32 %tmem, i32 %d0, i32 %d1) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.16x128b.x1.b32 [$0], {$1,$2};", "r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1) #0
  ret void
}

attributes #0 = { convergent }
