; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: a6962ae6c56aec0716a291570b7ac8e02bd1e4052ee151affa72d372f17faf3a.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.commit.cg2; route: inline PTX; source contract: TablegenSelectionChangesPtx
define void @probe_tcgen05_commit_cg2(i32 %mbar) #0 {
  call void asm sideeffect "tcgen05.commit.cta_group::2.mbarrier::arrive::one.b64 [$0];", "r,~{memory}"(i32 %mbar) #0
  ret void
}

attributes #0 = { convergent }
