; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 478f564b163dc9e806fded98a951c6e5a36e14d9f95fe5cb8d897ac914411697.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define void @probe_tensormap_replace_interleave_layout(ptr %tensor_map) {
  call void asm sideeffect "tensormap.replace.tile.interleave_layout.global.b1024.b32 [$0], $1;", "l,n,~{memory}"(ptr %tensor_map, i32 0)
  ret void
}
