/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated intrinsic target records: `movmatrix` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedPtxVersion, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[GeneratedIntrinsicTarget {
    marker: "v1:i0305",
    id: "movmatrix_trans_b16",
    abi_id: "i0305",
    dialect_op: "nvvm.movmatrix_trans_b16",
    variant: GeneratedIntrinsicVariant::Scalar,
    requirement: GeneratedTargetRequirement {
        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
        hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(75)]),
    },
    backend_requirements: &[
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LlvmNvptx,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LibNvvm,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
    ],
    selections: &[],
    llvm: None,
}];
