/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated intrinsic target records: `warp_shuffle` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedLlvmFacts, GeneratedPtxVersion, GeneratedSelectionAlternative,
    GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i0050",
        id: "shuffle_sync",
        abi_id: "i0050",
        dialect_op: "nvvm.shfl_sync_idx_i32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14989",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14990",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14991",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14992",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14993",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14994",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14995",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14996",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0051",
        id: "shuffle_xor_sync",
        abi_id: "i0051",
        dialect_op: "nvvm.shfl_sync_bfly_i32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14957",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14958",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14959",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14960",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14961",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14962",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14963",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14964",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0052",
        id: "shuffle_down_sync",
        abi_id: "i0052",
        dialect_op: "nvvm.shfl_sync_down_i32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14925",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14926",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14927",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14928",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14929",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14930",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14931",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14932",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0053",
        id: "shuffle_up_sync",
        abi_id: "i0053",
        dialect_op: "nvvm.shfl_sync_up_i32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14893",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14894",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14895",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14896",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14897",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14898",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14899",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14900",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0054",
        id: "shuffle_f32_sync",
        abi_id: "i0054",
        dialect_op: "nvvm.shfl_sync_idx_f32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_15005",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15006",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15007",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15008",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15009",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15010",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15011",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_15012",
                asm: "shfl.sync.idx.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0055",
        id: "shuffle_xor_f32_sync",
        abi_id: "i0055",
        dialect_op: "nvvm.shfl_sync_bfly_f32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14973",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14974",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14975",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14976",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14977",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14978",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14979",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14980",
                asm: "shfl.sync.bfly.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0056",
        id: "shuffle_down_f32_sync",
        abi_id: "i0056",
        dialect_op: "nvvm.shfl_sync_down_f32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14941",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14942",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14943",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14944",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14945",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14946",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14947",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14948",
                asm: "shfl.sync.down.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0057",
        id: "shuffle_up_f32_sync",
        abi_id: "i0057",
        dialect_op: "nvvm.shfl_sync_up_f32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "anonymous_14909",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14910",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14911",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14912",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14913",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14914",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14915",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "anonymous_14916",
                asm: "shfl.sync.up.b32 \t$dst, $src, $offset, $mask, $threadmask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrConvergent",
                "IntrInaccessibleMemOnly",
                "IntrNoCallback",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0058",
        id: "shuffle_u64_sync",
        abi_id: "i0058",
        dialect_op: "nvvm.shfl_sync_idx_i64",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0059",
        id: "shuffle_xor_u64_sync",
        abi_id: "i0059",
        dialect_op: "nvvm.shfl_sync_bfly_i64",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0060",
        id: "shuffle_down_u64_sync",
        abi_id: "i0060",
        dialect_op: "nvvm.shfl_sync_down_i64",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0061",
        id: "shuffle_up_u64_sync",
        abi_id: "i0061",
        dialect_op: "nvvm.shfl_sync_up_i64",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(60),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                30,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(30),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
];
