/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 38/0.1.0; intrinsic ABI: v1; catalog SHA-256: ea633a144ec6b66a832c0c37c02ed9fe69a5aaa8de22c89a8eb0edcecf29c6b5.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated collector predicates for intrinsic placeholder functions.

pub(crate) const GENERATED_INTRINSIC_ABI: u32 = 1;
pub(crate) const GENERATED_INTRINSIC_ABI_NAMESPACE: &str = "__cuda_oxide_intrinsic_abi_v1";
pub(crate) const GENERATED_INTRINSIC_CRATES: &[&str] = &["cuda_intrinsics", "cuda-intrinsics"];

pub(crate) const GENERATED_INTRINSIC_CANONICAL_PATHS: &[&str] = &[
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0070",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0080",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0044",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0064",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0074",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0040",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0041",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0042",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0277",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0278",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0279",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0280",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0281",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0282",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0003",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0007",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0011",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0002",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0006",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0010",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0296",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0325",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0326",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0327",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0324",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0322",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0323",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0283",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0284",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0276",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0263",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0264",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0265",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0275",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0266",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0267",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0268",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0272",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0273",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0274",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0269",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0270",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0271",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0090",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0086",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0088",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0091",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0087",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0089",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0092",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0093",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0094",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0101",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0103",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0104",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0102",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0095",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0096",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0081",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0071",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0084",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0083",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0259",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0261",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0260",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0262",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0085",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0082",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0032",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0033",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0030",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0031",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0321",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0293",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0286",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0287",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0313",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0315",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0314",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0312",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0062",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0072",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0063",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0073",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0285",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0004",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0008",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0012",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0290",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0016",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0037",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0038",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0039",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0036",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0035",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0025",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0026",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0027",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0028",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0013",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0029",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0320",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0048",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0047",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0046",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0045",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0068",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0078",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0098",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0308",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0306",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0307",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0097",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0100",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0099",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0309",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0310",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0311",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0067",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0077",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0161",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0158",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0105",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0106",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0110",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0117",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0111",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0118",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0112",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0113",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0120",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0119",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0162",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0159",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0141",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0149",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0142",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0150",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0108",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0121",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0114",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0122",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0143",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0144",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0152",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0151",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0115",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0116",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0124",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0123",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0145",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0153",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0146",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0154",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0147",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0148",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0156",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0155",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0107",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0160",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0157",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0125",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0129",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0126",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0130",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0127",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0128",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0132",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0131",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0133",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0137",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0134",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0138",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0135",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0136",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0140",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0139",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0109",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0219",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0223",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0220",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0224",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0221",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0222",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0226",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0225",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0163",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0167",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0164",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0168",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0165",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0166",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0170",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0169",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0211",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0215",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0212",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0216",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0187",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0191",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0188",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0192",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0213",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0214",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0218",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0217",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0189",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0190",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0194",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0193",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0203",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0207",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0204",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0208",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0205",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0206",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0210",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0209",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0171",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0175",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0172",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0176",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0173",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0174",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0178",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0177",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0227",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0228",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0229",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0230",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0231",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0232",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0233",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0234",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0235",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0236",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0237",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0238",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0239",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0240",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0241",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0242",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0243",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0244",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0245",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0246",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0247",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0248",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0249",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0250",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0251",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0195",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0199",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0196",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0200",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0179",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0183",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0180",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0184",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0197",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0198",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0202",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0201",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0181",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0182",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0186",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0185",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0305",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0066",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0076",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0316",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0069",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0079",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0289",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0292",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0015",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0014",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0297",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0252",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0254",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0256",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0257",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0253",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0258",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0255",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0017",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0022",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0021",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0020",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0019",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0018",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0023",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0024",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0056",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0052",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0060",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0054",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0050",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0058",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0057",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0053",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0061",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0055",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0051",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0059",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0288",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0301",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0302",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0303",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0304",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0065",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0075",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0049",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0034",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0001",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0005",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0009",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0299",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0298",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0300",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0294",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0295",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0043",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0291",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0318",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0317",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0319",
];

pub(crate) const GENERATED_INTRINSIC_PUBLIC_PATHS: &[&str] = &[
    "cuda_intrinsics::bf16x2::abs_bf16x2",
    "cuda_intrinsics::f16x2::abs_f16x2",
    "cuda_intrinsics::warp::active_mask",
    "cuda_intrinsics::bf16x2::add_bf16x2",
    "cuda_intrinsics::f16x2::add_f16x2",
    "cuda_intrinsics::warp::all_sync",
    "cuda_intrinsics::warp::any_sync",
    "cuda_intrinsics::warp::ballot_sync",
    "cuda_intrinsics::cluster::barrier_cluster_arrive",
    "cuda_intrinsics::cluster::barrier_cluster_arrive_aligned",
    "cuda_intrinsics::cluster::barrier_cluster_arrive_relaxed",
    "cuda_intrinsics::cluster::barrier_cluster_arrive_relaxed_aligned",
    "cuda_intrinsics::cluster::barrier_cluster_wait",
    "cuda_intrinsics::cluster::barrier_cluster_wait_aligned",
    "cuda_intrinsics::sreg::block_dim_x",
    "cuda_intrinsics::sreg::block_dim_y",
    "cuda_intrinsics::sreg::block_dim_z",
    "cuda_intrinsics::sreg::block_idx_x",
    "cuda_intrinsics::sreg::block_idx_y",
    "cuda_intrinsics::sreg::block_idx_z",
    "cuda_intrinsics::debug::breakpoint",
    "cuda_intrinsics::clc::clc_query_get_first_ctaid_x",
    "cuda_intrinsics::clc::clc_query_get_first_ctaid_y",
    "cuda_intrinsics::clc::clc_query_get_first_ctaid_z",
    "cuda_intrinsics::clc::clc_query_is_canceled",
    "cuda_intrinsics::clc::clc_try_cancel",
    "cuda_intrinsics::clc::clc_try_cancel_multicast",
    "cuda_intrinsics::debug::clock",
    "cuda_intrinsics::debug::clock64",
    "cuda_intrinsics::sreg::cluster_block_count",
    "cuda_intrinsics::sreg::cluster_block_idx_x",
    "cuda_intrinsics::sreg::cluster_block_idx_y",
    "cuda_intrinsics::sreg::cluster_block_idx_z",
    "cuda_intrinsics::sreg::cluster_block_rank",
    "cuda_intrinsics::sreg::cluster_dim_x",
    "cuda_intrinsics::sreg::cluster_dim_y",
    "cuda_intrinsics::sreg::cluster_dim_z",
    "cuda_intrinsics::sreg::cluster_grid_dim_x",
    "cuda_intrinsics::sreg::cluster_grid_dim_y",
    "cuda_intrinsics::sreg::cluster_grid_dim_z",
    "cuda_intrinsics::sreg::cluster_idx_x",
    "cuda_intrinsics::sreg::cluster_idx_y",
    "cuda_intrinsics::sreg::cluster_idx_z",
    "cuda_intrinsics::async_copy::cp_async_ca_16",
    "cuda_intrinsics::async_copy::cp_async_ca_4",
    "cuda_intrinsics::async_copy::cp_async_ca_8",
    "cuda_intrinsics::async_copy::cp_async_ca_zfill_16",
    "cuda_intrinsics::async_copy::cp_async_ca_zfill_4",
    "cuda_intrinsics::async_copy::cp_async_ca_zfill_8",
    "cuda_intrinsics::async_copy::cp_async_cg_16",
    "cuda_intrinsics::async_copy::cp_async_cg_zfill_16",
    "cuda_intrinsics::async_copy::cp_async_commit_group",
    "cuda_intrinsics::async_copy::cp_async_mbarrier_arrive",
    "cuda_intrinsics::async_copy::cp_async_mbarrier_arrive_noinc",
    "cuda_intrinsics::async_copy::cp_async_mbarrier_arrive_noinc_shared",
    "cuda_intrinsics::async_copy::cp_async_mbarrier_arrive_shared",
    "cuda_intrinsics::async_copy::cp_async_wait_all",
    "cuda_intrinsics::async_copy::cp_async_wait_group",
    "cuda_intrinsics::convert::cvt_f16x2_f32",
    "cuda_intrinsics::convert::cvt_f32x2_bf16x2",
    "cuda_intrinsics::convert::cvt_rn_relu_bf16x2_f32",
    "cuda_intrinsics::convert::cvt_rn_relu_f16x2_f32",
    "cuda_intrinsics::convert::cvt_rn_satfinite_e4m3x2_f32",
    "cuda_intrinsics::convert::cvt_rn_satfinite_e5m2x2_f32",
    "cuda_intrinsics::convert::cvt_rn_satfinite_relu_e4m3x2_f32",
    "cuda_intrinsics::convert::cvt_rn_satfinite_relu_e5m2x2_f32",
    "cuda_intrinsics::convert::cvt_rz_bf16x2_f32",
    "cuda_intrinsics::convert::cvt_rz_f16x2_f32",
    "cuda_intrinsics::dotprod::dp2a_s32",
    "cuda_intrinsics::dotprod::dp2a_u32",
    "cuda_intrinsics::dotprod::dp4a_s32",
    "cuda_intrinsics::dotprod::dp4a_u32",
    "cuda_intrinsics::cluster::dsmem_read_u32",
    "cuda_intrinsics::shared::dynamic_smem_size",
    "cuda_intrinsics::grid::envreg1",
    "cuda_intrinsics::grid::envreg2",
    "cuda_intrinsics::barrier::fence_mbarrier_init_release_cluster",
    "cuda_intrinsics::barrier::fence_proxy_async_generic_acquire_shared_cluster_cluster",
    "cuda_intrinsics::barrier::fence_proxy_async_generic_release_shared_cta_cluster",
    "cuda_intrinsics::barrier::fence_proxy_async_shared_cta",
    "cuda_intrinsics::bf16x2::fma_bf16x2",
    "cuda_intrinsics::f16x2::fma_f16x2",
    "cuda_intrinsics::bf16x2::fma_relu_bf16x2",
    "cuda_intrinsics::f16x2::fma_relu_f16x2",
    "cuda_intrinsics::debug::globaltimer",
    "cuda_intrinsics::sreg::grid_dim_x",
    "cuda_intrinsics::sreg::grid_dim_y",
    "cuda_intrinsics::sreg::grid_dim_z",
    "cuda_intrinsics::thread::gridid",
    "cuda_intrinsics::sreg::lane_id",
    "cuda_intrinsics::sreg::lanemask_eq",
    "cuda_intrinsics::sreg::lanemask_ge",
    "cuda_intrinsics::sreg::lanemask_gt",
    "cuda_intrinsics::sreg::lanemask_le",
    "cuda_intrinsics::sreg::lanemask_lt",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x1_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x1_trans_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x2_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x2_trans_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x4_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x4_trans_b16",
    "cuda_intrinsics::cluster::map_shared_rank",
    "cuda_intrinsics::warp::match_all_i64_sync",
    "cuda_intrinsics::warp::match_all_sync",
    "cuda_intrinsics::warp::match_any_i64_sync",
    "cuda_intrinsics::warp::match_any_sync",
    "cuda_intrinsics::bf16x2::max_bf16x2",
    "cuda_intrinsics::f16x2::max_f16x2",
    "cuda_intrinsics::barrier::mbarrier_arrive",
    "cuda_intrinsics::barrier::mbarrier_arrive_cluster",
    "cuda_intrinsics::barrier::mbarrier_arrive_expect_tx",
    "cuda_intrinsics::barrier::mbarrier_arrive_expect_tx_cluster",
    "cuda_intrinsics::barrier::mbarrier_init",
    "cuda_intrinsics::barrier::mbarrier_inval",
    "cuda_intrinsics::barrier::mbarrier_test_wait",
    "cuda_intrinsics::barrier::mbarrier_try_wait",
    "cuda_intrinsics::barrier::mbarrier_try_wait_parity",
    "cuda_intrinsics::barrier::mbarrier_try_wait_parity_cluster",
    "cuda_intrinsics::bf16x2::min_bf16x2",
    "cuda_intrinsics::f16x2::min_f16x2",
    "cuda_intrinsics::matrix::mma_m16n8k128_s32_b1_and_popc",
    "cuda_intrinsics::matrix::mma_m16n8k128_s32_b1_xor_popc",
    "cuda_intrinsics::matrix::mma_m16n8k16_f32_bf16",
    "cuda_intrinsics::matrix::mma_m16n8k16_f32_f16",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_s8",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_u8",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k16_s32_u8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k256_s32_b1_and_popc",
    "cuda_intrinsics::matrix::mma_m16n8k256_s32_b1_xor_popc",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s4",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s8",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u4",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u8",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k32_s32_u8_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_s4",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_u4",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k64_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_m16n8k8_f32_tf32",
    "cuda_intrinsics::matrix::mma_m8n8k128_s32_b1_and_popc",
    "cuda_intrinsics::matrix::mma_m8n8k128_s32_b1_xor_popc",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_s8",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_u8",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k16_s32_u8_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_s4",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_u4",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k32_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_m8n8k4_f64",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_s4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_u4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k128_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_s8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_u8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k32_s32_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_m16n8k64_s32_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_s4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_u4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k128_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_s8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_u8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k32_s32_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e2m1_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e2m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e3m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e4m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e5m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e2m1_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e2m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e3m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e4m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e5m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e2m1_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e2m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e3m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e4m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e5m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e2m1_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e2m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e3m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e4m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e5m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e2m1_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e2m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e3m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e4m3_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e5m2_f32",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s4_u4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s4_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s8_u8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_s8_u8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u4_s4",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u4_s4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u4_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u8_s8",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u8_s8_satfinite",
    "cuda_intrinsics::matrix::mma_sp_ordered_metadata_m16n8k64_s32_u8_satfinite",
    "cuda_intrinsics::matrix::movmatrix_trans_b16",
    "cuda_intrinsics::bf16x2::mul_bf16x2",
    "cuda_intrinsics::f16x2::mul_f16x2",
    "cuda_intrinsics::barrier::nanosleep",
    "cuda_intrinsics::bf16x2::neg_bf16x2",
    "cuda_intrinsics::f16x2::neg_f16x2",
    "cuda_intrinsics::thread::nsmid",
    "cuda_intrinsics::warp::nwarpid",
    "cuda_intrinsics::atomic::atom_add_bf16x2",
    "cuda_intrinsics::atomic::atom_add_f16x2",
    "cuda_intrinsics::debug::pmevent",
    "cuda_intrinsics::prmt::prmt",
    "cuda_intrinsics::prmt::prmt_b4e",
    "cuda_intrinsics::prmt::prmt_ecl",
    "cuda_intrinsics::prmt::prmt_ecr",
    "cuda_intrinsics::prmt::prmt_f4e",
    "cuda_intrinsics::prmt::prmt_rc16",
    "cuda_intrinsics::prmt::prmt_rc8",
    "cuda_intrinsics::warp::redux_sync_add",
    "cuda_intrinsics::warp::redux_sync_and",
    "cuda_intrinsics::warp::redux_sync_max_i32",
    "cuda_intrinsics::warp::redux_sync_max_u32",
    "cuda_intrinsics::warp::redux_sync_min_i32",
    "cuda_intrinsics::warp::redux_sync_min_u32",
    "cuda_intrinsics::warp::redux_sync_or",
    "cuda_intrinsics::warp::redux_sync_xor",
    "cuda_intrinsics::warp::shuffle_down_f32_sync",
    "cuda_intrinsics::warp::shuffle_down_sync",
    "cuda_intrinsics::warp::shuffle_down_u64_sync",
    "cuda_intrinsics::warp::shuffle_f32_sync",
    "cuda_intrinsics::warp::shuffle_sync",
    "cuda_intrinsics::warp::shuffle_u64_sync",
    "cuda_intrinsics::warp::shuffle_up_f32_sync",
    "cuda_intrinsics::warp::shuffle_up_sync",
    "cuda_intrinsics::warp::shuffle_up_u64_sync",
    "cuda_intrinsics::warp::shuffle_xor_f32_sync",
    "cuda_intrinsics::warp::shuffle_xor_sync",
    "cuda_intrinsics::warp::shuffle_xor_u64_sync",
    "cuda_intrinsics::thread::smid",
    "cuda_intrinsics::matrix::stmatrix_m8n8_x2_b16",
    "cuda_intrinsics::matrix::stmatrix_m8n8_x2_trans_b16",
    "cuda_intrinsics::matrix::stmatrix_m8n8_x4_b16",
    "cuda_intrinsics::matrix::stmatrix_m8n8_x4_trans_b16",
    "cuda_intrinsics::bf16x2::sub_bf16x2",
    "cuda_intrinsics::f16x2::sub_f16x2",
    "cuda_intrinsics::warp::sync_mask",
    "cuda_intrinsics::thread::sync_threads",
    "cuda_intrinsics::sreg::thread_idx_x",
    "cuda_intrinsics::sreg::thread_idx_y",
    "cuda_intrinsics::sreg::thread_idx_z",
    "cuda_intrinsics::fence::threadfence",
    "cuda_intrinsics::fence::threadfence_block",
    "cuda_intrinsics::fence::threadfence_system",
    "cuda_intrinsics::shared::total_smem_size",
    "cuda_intrinsics::debug::trap",
    "cuda_intrinsics::warp::uni_sync",
    "cuda_intrinsics::warp::warpid",
    "cuda_intrinsics::wgmma::wgmma_commit_group",
    "cuda_intrinsics::wgmma::wgmma_fence",
    "cuda_intrinsics::wgmma::wgmma_wait_group",
];

pub(crate) fn is_generated_intrinsic_crate(crate_name: &str) -> bool {
    GENERATED_INTRINSIC_CRATES.contains(&crate_name)
}

pub(crate) fn is_generated_intrinsic_canonical_path(path: &str) -> bool {
    matches!(
        path,
        "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0070"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0080"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0044"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0064"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0074"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0040"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0041"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0042"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0277"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0278"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0279"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0280"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0281"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0282"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0003"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0007"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0011"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0002"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0006"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0010"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0296"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0325"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0326"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0327"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0324"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0322"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0323"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0283"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0284"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0276"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0263"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0264"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0265"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0275"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0266"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0267"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0268"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0272"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0273"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0274"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0269"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0270"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0271"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0090"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0086"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0088"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0091"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0087"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0089"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0092"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0093"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0094"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0101"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0103"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0104"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0102"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0095"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0096"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0081"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0071"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0084"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0083"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0259"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0261"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0260"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0262"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0085"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0082"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0032"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0033"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0030"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0031"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0321"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0293"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0286"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0287"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0313"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0315"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0314"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0312"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0062"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0072"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0063"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0073"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0285"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0004"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0008"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0012"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0290"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0016"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0037"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0038"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0039"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0036"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0035"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0025"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0026"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0027"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0028"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0013"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0029"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0320"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0048"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0047"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0046"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0045"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0068"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0078"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0098"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0308"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0306"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0307"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0097"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0100"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0099"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0309"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0310"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0311"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0067"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0077"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0161"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0158"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0105"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0106"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0110"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0117"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0111"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0118"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0112"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0113"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0120"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0119"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0162"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0159"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0141"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0149"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0142"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0150"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0108"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0121"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0114"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0122"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0143"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0144"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0152"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0151"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0115"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0116"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0124"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0123"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0145"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0153"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0146"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0154"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0147"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0148"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0156"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0155"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0107"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0160"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0157"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0125"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0129"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0126"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0130"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0127"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0128"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0132"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0131"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0133"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0137"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0134"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0138"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0135"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0136"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0140"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0139"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0109"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0219"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0223"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0220"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0224"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0221"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0222"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0226"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0225"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0163"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0167"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0164"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0168"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0165"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0166"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0170"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0169"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0211"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0215"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0212"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0216"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0187"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0191"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0188"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0192"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0213"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0214"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0218"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0217"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0189"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0190"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0194"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0193"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0203"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0207"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0204"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0208"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0205"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0206"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0210"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0209"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0171"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0175"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0172"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0176"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0173"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0174"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0178"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0177"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0227"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0228"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0229"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0230"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0231"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0232"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0233"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0234"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0235"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0236"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0237"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0238"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0239"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0240"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0241"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0242"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0243"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0244"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0245"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0246"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0247"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0248"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0249"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0250"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0251"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0195"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0199"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0196"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0200"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0179"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0183"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0180"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0184"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0197"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0198"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0202"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0201"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0181"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0182"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0186"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0185"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0305"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0066"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0076"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0316"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0069"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0079"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0289"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0292"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0015"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0014"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0297"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0252"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0254"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0256"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0257"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0253"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0258"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0255"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0017"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0022"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0021"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0020"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0019"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0018"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0023"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0024"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0056"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0052"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0060"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0054"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0050"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0058"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0057"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0053"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0061"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0055"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0051"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0059"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0288"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0301"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0302"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0303"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0304"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0065"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0075"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0049"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0034"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0001"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0005"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0009"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0299"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0298"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0300"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0294"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0295"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0043"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0291"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0318"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0317"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0319"
    )
}

pub(crate) fn is_generated_intrinsic_compatibility_path(path: &str) -> bool {
    matches!(
        path,
        "cuda_device::bf16x2::abs_bf16x2"
            | "cuda_device::f16x2::abs_f16x2"
            | "cuda_device::warp::active_mask"
            | "cuda_device::bf16x2::add_bf16x2"
            | "cuda_device::f16x2::add_f16x2"
            | "cuda_device::warp::all_sync"
            | "cuda_device::warp::any_sync"
            | "cuda_device::warp::ballot_sync"
            | "cuda_device::cluster::barrier_cluster_arrive"
            | "cuda_device::cluster::barrier_cluster_arrive_aligned"
            | "cuda_device::cluster::barrier_cluster_arrive_relaxed"
            | "cuda_device::cluster::barrier_cluster_arrive_relaxed_aligned"
            | "cuda_device::cluster::barrier_cluster_wait"
            | "cuda_device::cluster::barrier_cluster_wait_aligned"
            | "cuda_device::thread::blockDim_x"
            | "cuda_device::blockDim_x"
            | "cuda_device::thread::blockDim_y"
            | "cuda_device::blockDim_y"
            | "cuda_device::thread::blockDim_z"
            | "cuda_device::blockDim_z"
            | "cuda_device::thread::blockIdx_x"
            | "cuda_device::blockIdx_x"
            | "cuda_device::thread::blockIdx_y"
            | "cuda_device::blockIdx_y"
            | "cuda_device::thread::blockIdx_z"
            | "cuda_device::blockIdx_z"
            | "cuda_device::debug::breakpoint"
            | "cuda_device::clc::clc_query_get_first_ctaid_x"
            | "cuda_device::clc::clc_query_get_first_ctaid_y"
            | "cuda_device::clc::clc_query_get_first_ctaid_z"
            | "cuda_device::clc::clc_query_is_canceled"
            | "cuda_device::clc::clc_try_cancel"
            | "cuda_device::clc::clc_try_cancel_multicast"
            | "cuda_device::debug::clock"
            | "cuda_device::debug::clock64"
            | "cuda_device::cluster::cluster_ctaidX"
            | "cuda_device::cluster::cluster_ctaidY"
            | "cuda_device::cluster::cluster_ctaidZ"
            | "cuda_device::cluster::cluster_nctaidX"
            | "cuda_device::cluster::cluster_nctaidY"
            | "cuda_device::cluster::cluster_nctaidZ"
            | "cuda_device::cluster::__cluster_grid_dimX"
            | "cuda_device::cluster::__cluster_grid_dimY"
            | "cuda_device::cluster::__cluster_grid_dimZ"
            | "cuda_device::cluster::__cluster_idxX"
            | "cuda_device::cluster::__cluster_idxY"
            | "cuda_device::cluster::__cluster_idxZ"
            | "cuda_device::async_copy::cp_async_ca_16"
            | "cuda_device::async_copy::cp_async_ca_4"
            | "cuda_device::async_copy::cp_async_ca_8"
            | "cuda_device::async_copy::cp_async_ca_zfill_16"
            | "cuda_device::async_copy::cp_async_ca_zfill_4"
            | "cuda_device::async_copy::cp_async_ca_zfill_8"
            | "cuda_device::async_copy::cp_async_cg_16"
            | "cuda_device::async_copy::cp_async_cg_zfill_16"
            | "cuda_device::async_copy::cp_async_commit_group"
            | "cuda_device::async_copy::cp_async_mbarrier_arrive"
            | "cuda_device::async_copy::cp_async_mbarrier_arrive_noinc"
            | "cuda_device::async_copy::cp_async_mbarrier_arrive_noinc_shared"
            | "cuda_device::async_copy::cp_async_mbarrier_arrive_shared"
            | "cuda_device::async_copy::cp_async_wait_all"
            | "cuda_device::async_copy::cp_async_wait_group"
            | "cuda_device::convert::cvt_f16x2_f32"
            | "cuda_device::tcgen05::cvt_f32x2_bf16x2"
            | "cuda_device::convert::cvt_rn_relu_bf16x2_f32"
            | "cuda_device::convert::cvt_rn_relu_f16x2_f32"
            | "cuda_device::convert::cvt_rn_satfinite_e4m3x2_f32"
            | "cuda_device::convert::cvt_rn_satfinite_e5m2x2_f32"
            | "cuda_device::convert::cvt_rn_satfinite_relu_e4m3x2_f32"
            | "cuda_device::convert::cvt_rn_satfinite_relu_e5m2x2_f32"
            | "cuda_device::convert::cvt_rz_bf16x2_f32"
            | "cuda_device::convert::cvt_rz_f16x2_f32"
            | "cuda_device::dotprod::dp2a_s32"
            | "cuda_device::dotprod::dp2a_u32"
            | "cuda_device::dotprod::dp4a_s32"
            | "cuda_device::dotprod::dp4a_u32"
            | "cuda_device::cluster::dsmem_read_u32"
            | "cuda_device::shared::dynamic_smem_size"
            | "cuda_device::grid::envreg1"
            | "cuda_device::grid::envreg2"
            | "cuda_device::barrier::fence_mbarrier_init_release_cluster"
            | "cuda_device::barrier::fence_proxy_async_generic_acquire_shared_cluster_cluster"
            | "cuda_device::barrier::fence_proxy_async_generic_release_shared_cta_cluster"
            | "cuda_device::barrier::fence_proxy_async_shared_cta"
            | "cuda_device::bf16x2::fma_bf16x2"
            | "cuda_device::f16x2::fma_f16x2"
            | "cuda_device::bf16x2::fma_relu_bf16x2"
            | "cuda_device::f16x2::fma_relu_f16x2"
            | "cuda_device::debug::globaltimer"
            | "cuda_device::thread::gridDim_x"
            | "cuda_device::gridDim_x"
            | "cuda_device::thread::gridDim_y"
            | "cuda_device::gridDim_y"
            | "cuda_device::thread::gridDim_z"
            | "cuda_device::gridDim_z"
            | "cuda_device::thread::gridid"
            | "cuda_device::gridid"
            | "cuda_device::warp::lane_id"
            | "cuda_device::warp::lanemask_eq"
            | "cuda_device::warp::lanemask_ge"
            | "cuda_device::warp::lanemask_gt"
            | "cuda_device::warp::lanemask_le"
            | "cuda_device::warp::lanemask_lt"
            | "cuda_device::wmma::ldmatrix_x1"
            | "cuda_device::wmma::ldmatrix_x1_trans"
            | "cuda_device::wmma::ldmatrix_x2"
            | "cuda_device::wmma::ldmatrix_x2_trans"
            | "cuda_device::wmma::ldmatrix_x4"
            | "cuda_device::wmma::ldmatrix_x4_trans"
            | "cuda_device::cluster::map_shared_rank"
            | "cuda_device::cluster::map_shared_rank_mut"
            | "cuda_device::warp::match_all_i64_sync"
            | "cuda_device::warp::match_all_sync"
            | "cuda_device::warp::match_any_i64_sync"
            | "cuda_device::warp::match_any_sync"
            | "cuda_device::bf16x2::max_bf16x2"
            | "cuda_device::f16x2::max_f16x2"
            | "cuda_device::barrier::mbarrier_arrive"
            | "cuda_device::barrier::mbarrier_arrive_cluster"
            | "cuda_device::barrier::mbarrier_arrive_expect_tx"
            | "cuda_device::barrier::mbarrier_arrive_expect_tx_cluster"
            | "cuda_device::barrier::mbarrier_init"
            | "cuda_device::barrier::mbarrier_inval"
            | "cuda_device::barrier::mbarrier_test_wait"
            | "cuda_device::barrier::mbarrier_try_wait"
            | "cuda_device::barrier::mbarrier_try_wait_parity"
            | "cuda_device::barrier::mbarrier_try_wait_parity_cluster"
            | "cuda_device::bf16x2::min_bf16x2"
            | "cuda_device::f16x2::min_f16x2"
            | "cuda_device::wmma::mma_m16n8k128_s32_b1_and_popc"
            | "cuda_device::wmma::mma_m16n8k128_s32_b1_xor_popc"
            | "cuda_device::wmma::mma_m16n8k16_f32_bf16"
            | "cuda_device::wmma::mma_m16n8k16_f32_f16"
            | "cuda_device::wmma::mma_m16n8k16_s32_s8"
            | "cuda_device::wmma::mma_m16n8k16_s32_s8_satfinite"
            | "cuda_device::wmma::mma_m16n8k16_s32_s8_u8"
            | "cuda_device::wmma::mma_m16n8k16_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_m16n8k16_s32_u8"
            | "cuda_device::wmma::mma_m16n8k16_s32_u8_s8"
            | "cuda_device::wmma::mma_m16n8k16_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_m16n8k16_s32_u8_satfinite"
            | "cuda_device::wmma::mma_m16n8k256_s32_b1_and_popc"
            | "cuda_device::wmma::mma_m16n8k256_s32_b1_xor_popc"
            | "cuda_device::wmma::mma_m16n8k32_s32_s4"
            | "cuda_device::wmma::mma_m16n8k32_s32_s4_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_s4_u4"
            | "cuda_device::wmma::mma_m16n8k32_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_s8"
            | "cuda_device::wmma::mma_m16n8k32_s32_s8_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_s8_u8"
            | "cuda_device::wmma::mma_m16n8k32_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_u4"
            | "cuda_device::wmma::mma_m16n8k32_s32_u4_s4"
            | "cuda_device::wmma::mma_m16n8k32_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_u4_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_u8"
            | "cuda_device::wmma::mma_m16n8k32_s32_u8_s8"
            | "cuda_device::wmma::mma_m16n8k32_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_m16n8k32_s32_u8_satfinite"
            | "cuda_device::wmma::mma_m16n8k64_s32_s4"
            | "cuda_device::wmma::mma_m16n8k64_s32_s4_satfinite"
            | "cuda_device::wmma::mma_m16n8k64_s32_s4_u4"
            | "cuda_device::wmma::mma_m16n8k64_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_m16n8k64_s32_u4"
            | "cuda_device::wmma::mma_m16n8k64_s32_u4_s4"
            | "cuda_device::wmma::mma_m16n8k64_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_m16n8k64_s32_u4_satfinite"
            | "cuda_device::wmma::mma_m16n8k8_f32_tf32"
            | "cuda_device::wmma::mma_m8n8k128_s32_b1_and_popc"
            | "cuda_device::wmma::mma_m8n8k128_s32_b1_xor_popc"
            | "cuda_device::wmma::mma_m8n8k16_s32_s8"
            | "cuda_device::wmma::mma_m8n8k16_s32_s8_satfinite"
            | "cuda_device::wmma::mma_m8n8k16_s32_s8_u8"
            | "cuda_device::wmma::mma_m8n8k16_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_m8n8k16_s32_u8"
            | "cuda_device::wmma::mma_m8n8k16_s32_u8_s8"
            | "cuda_device::wmma::mma_m8n8k16_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_m8n8k16_s32_u8_satfinite"
            | "cuda_device::wmma::mma_m8n8k32_s32_s4"
            | "cuda_device::wmma::mma_m8n8k32_s32_s4_satfinite"
            | "cuda_device::wmma::mma_m8n8k32_s32_s4_u4"
            | "cuda_device::wmma::mma_m8n8k32_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_m8n8k32_s32_u4"
            | "cuda_device::wmma::mma_m8n8k32_s32_u4_s4"
            | "cuda_device::wmma::mma_m8n8k32_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_m8n8k32_s32_u4_satfinite"
            | "cuda_device::wmma::mma_m8n8k4_f64"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_s4"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_s4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_s4_u4"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_u4"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_u4_s4"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k128_s32_u4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_s8"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_s8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_s8_u8"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_u8"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_u8_s8"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k32_s32_u8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s4"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s4_u4"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s8"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s8_u8"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u4"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u4_s4"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u4_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u8"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u8_s8"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_sp_m16n8k64_s32_u8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_s4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_s4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_s4_u4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_u4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_u4_s4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k128_s32_u4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_s8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_s8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_s8_u8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_u8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_u8_s8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k32_s32_u8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e2m1_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e2m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e3m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e4m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m1_e5m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e2m1_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e2m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e3m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e4m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e2m3_e5m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e2m1_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e2m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e3m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e4m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e3m2_e5m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e2m1_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e2m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e3m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e4m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e4m3_e5m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e2m1_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e2m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e3m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e4m3_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_kind_f8f6f4_f32_e5m2_e5m2_f32"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s4_u4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s4_u4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s8_u8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_s8_u8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u4_s4"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u4_s4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u4_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u8_s8"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u8_s8_satfinite"
            | "cuda_device::wmma::mma_sp_ordered_metadata_m16n8k64_s32_u8_satfinite"
            | "cuda_device::wmma::movmatrix_trans_b16"
            | "cuda_device::bf16x2::mul_bf16x2"
            | "cuda_device::f16x2::mul_f16x2"
            | "cuda_device::barrier::nanosleep"
            | "cuda_device::bf16x2::neg_bf16x2"
            | "cuda_device::f16x2::neg_f16x2"
            | "cuda_device::thread::nsmid"
            | "cuda_device::nsmid"
            | "cuda_device::warp::nwarpid"
            | "cuda_device::atomic::atom_add_bf16x2"
            | "cuda_device::atomic::atom_add_f16x2"
            | "cuda_device::debug::__prof_trigger"
            | "cuda_device::prmt::prmt"
            | "cuda_device::prmt::prmt_b4e"
            | "cuda_device::prmt::prmt_ecl"
            | "cuda_device::prmt::prmt_ecr"
            | "cuda_device::prmt::prmt_f4e"
            | "cuda_device::prmt::prmt_rc16"
            | "cuda_device::prmt::prmt_rc8"
            | "cuda_device::warp::redux_sync_add"
            | "cuda_device::warp::redux_sync_and"
            | "cuda_device::warp::redux_sync_max_i32"
            | "cuda_device::warp::redux_sync_max_u32"
            | "cuda_device::warp::redux_sync_min_i32"
            | "cuda_device::warp::redux_sync_min_u32"
            | "cuda_device::warp::redux_sync_or"
            | "cuda_device::warp::redux_sync_xor"
            | "cuda_device::warp::shuffle_down_f32_sync"
            | "cuda_device::warp::shuffle_down_sync"
            | "cuda_device::warp::shuffle_down_u64_sync"
            | "cuda_device::warp::shuffle_f32_sync"
            | "cuda_device::warp::shuffle_sync"
            | "cuda_device::warp::shuffle_u64_sync"
            | "cuda_device::warp::shuffle_up_f32_sync"
            | "cuda_device::warp::shuffle_up_sync"
            | "cuda_device::warp::shuffle_up_u64_sync"
            | "cuda_device::warp::shuffle_xor_f32_sync"
            | "cuda_device::warp::shuffle_xor_sync"
            | "cuda_device::warp::shuffle_xor_u64_sync"
            | "cuda_device::thread::smid"
            | "cuda_device::smid"
            | "cuda_device::tcgen05::stmatrix_m8n8_x2"
            | "cuda_device::tcgen05::stmatrix_m8n8_x2_trans"
            | "cuda_device::tcgen05::stmatrix_m8n8_x4"
            | "cuda_device::tcgen05::stmatrix_m8n8_x4_trans"
            | "cuda_device::bf16x2::sub_bf16x2"
            | "cuda_device::f16x2::sub_f16x2"
            | "cuda_device::warp::sync_mask"
            | "cuda_device::thread::sync_threads"
            | "cuda_device::sync_threads"
            | "cuda_device::thread::threadIdx_x"
            | "cuda_device::threadIdx_x"
            | "cuda_device::thread::threadIdx_y"
            | "cuda_device::threadIdx_y"
            | "cuda_device::thread::threadIdx_z"
            | "cuda_device::threadIdx_z"
            | "cuda_device::fence::threadfence"
            | "cuda_device::threadfence"
            | "cuda_device::fence::threadfence_block"
            | "cuda_device::threadfence_block"
            | "cuda_device::fence::threadfence_system"
            | "cuda_device::threadfence_system"
            | "cuda_device::shared::total_smem_size"
            | "cuda_device::debug::trap"
            | "cuda_device::warp::warpid"
            | "cuda_device::wgmma::wgmma_commit_group"
            | "cuda_device::wgmma::wgmma_fence"
            | "cuda_device::wgmma::__wgmma_wait_group"
    )
}

pub(crate) fn is_generated_intrinsic_placeholder(crate_name: &str, path: &str) -> bool {
    if is_generated_intrinsic_crate(crate_name) {
        is_generated_intrinsic_canonical_path(path)
    } else if matches!(crate_name, "cuda_device" | "cuda-device") {
        is_generated_intrinsic_compatibility_path(path)
    } else {
        false
    }
}
