/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 9/0.1.0; intrinsic ABI: v1; catalog SHA-256: cc84dea1ffd27a915e733024bcbf3e57cb3d84a4fe9b6a0deb8afd31e53202dd.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated collector predicates for intrinsic placeholder functions.

pub(crate) const GENERATED_INTRINSIC_ABI: u32 = 1;
pub(crate) const GENERATED_INTRINSIC_ABI_NAMESPACE: &str = "__cuda_oxide_intrinsic_abi_v1";
pub(crate) const GENERATED_INTRINSIC_CRATES: &[&str] = &["cuda_intrinsics", "cuda-intrinsics"];

pub(crate) const GENERATED_INTRINSIC_CANONICAL_PATHS: &[&str] = &[
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0044",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0040",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0041",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0042",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0003",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0007",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0011",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0002",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0006",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0010",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0032",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0033",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0030",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0031",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0004",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0008",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0012",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0016",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0037",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0038",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0039",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0036",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0035",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0025",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0026",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0027",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0028",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0013",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0029",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0048",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0047",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0046",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0045",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0015",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0014",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0017",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0022",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0021",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0020",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0019",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0018",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0023",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0024",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0056",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0052",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0054",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0050",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0057",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0053",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0055",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0051",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0049",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0034",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0001",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0005",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0009",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0043",
];

pub(crate) const GENERATED_INTRINSIC_PUBLIC_PATHS: &[&str] = &[
    "cuda_intrinsics::warp::active_mask",
    "cuda_intrinsics::warp::all_sync",
    "cuda_intrinsics::warp::any_sync",
    "cuda_intrinsics::warp::ballot_sync",
    "cuda_intrinsics::sreg::block_dim_x",
    "cuda_intrinsics::sreg::block_dim_y",
    "cuda_intrinsics::sreg::block_dim_z",
    "cuda_intrinsics::sreg::block_idx_x",
    "cuda_intrinsics::sreg::block_idx_y",
    "cuda_intrinsics::sreg::block_idx_z",
    "cuda_intrinsics::dotprod::dp2a_s32",
    "cuda_intrinsics::dotprod::dp2a_u32",
    "cuda_intrinsics::dotprod::dp4a_s32",
    "cuda_intrinsics::dotprod::dp4a_u32",
    "cuda_intrinsics::sreg::grid_dim_x",
    "cuda_intrinsics::sreg::grid_dim_y",
    "cuda_intrinsics::sreg::grid_dim_z",
    "cuda_intrinsics::sreg::lane_id",
    "cuda_intrinsics::sreg::lanemask_eq",
    "cuda_intrinsics::sreg::lanemask_ge",
    "cuda_intrinsics::sreg::lanemask_gt",
    "cuda_intrinsics::sreg::lanemask_le",
    "cuda_intrinsics::sreg::lanemask_lt",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x1_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x1_trans_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x2_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x2_trans_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x4_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x4_trans_b16",
    "cuda_intrinsics::warp::match_all_i64_sync",
    "cuda_intrinsics::warp::match_all_sync",
    "cuda_intrinsics::warp::match_any_i64_sync",
    "cuda_intrinsics::warp::match_any_sync",
    "cuda_intrinsics::atomic::atom_add_bf16x2",
    "cuda_intrinsics::atomic::atom_add_f16x2",
    "cuda_intrinsics::warp::redux_sync_add",
    "cuda_intrinsics::warp::redux_sync_and",
    "cuda_intrinsics::warp::redux_sync_max_i32",
    "cuda_intrinsics::warp::redux_sync_max_u32",
    "cuda_intrinsics::warp::redux_sync_min_i32",
    "cuda_intrinsics::warp::redux_sync_min_u32",
    "cuda_intrinsics::warp::redux_sync_or",
    "cuda_intrinsics::warp::redux_sync_xor",
    "cuda_intrinsics::warp::shuffle_down_f32_sync",
    "cuda_intrinsics::warp::shuffle_down_sync",
    "cuda_intrinsics::warp::shuffle_f32_sync",
    "cuda_intrinsics::warp::shuffle_sync",
    "cuda_intrinsics::warp::shuffle_up_f32_sync",
    "cuda_intrinsics::warp::shuffle_up_sync",
    "cuda_intrinsics::warp::shuffle_xor_f32_sync",
    "cuda_intrinsics::warp::shuffle_xor_sync",
    "cuda_intrinsics::warp::sync_mask",
    "cuda_intrinsics::thread::sync_threads",
    "cuda_intrinsics::sreg::thread_idx_x",
    "cuda_intrinsics::sreg::thread_idx_y",
    "cuda_intrinsics::sreg::thread_idx_z",
    "cuda_intrinsics::warp::uni_sync",
];

pub(crate) fn is_generated_intrinsic_crate(crate_name: &str) -> bool {
    GENERATED_INTRINSIC_CRATES.contains(&crate_name)
}

pub(crate) fn is_generated_intrinsic_canonical_path(path: &str) -> bool {
    matches!(
        path,
        "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0044"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0040"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0041"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0042"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0003"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0007"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0011"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0002"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0006"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0010"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0032"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0033"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0030"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0031"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0004"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0008"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0012"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0016"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0037"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0038"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0039"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0036"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0035"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0025"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0026"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0027"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0028"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0013"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0029"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0048"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0047"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0046"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0045"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0015"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0014"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0017"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0022"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0021"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0020"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0019"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0018"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0023"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0024"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0056"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0052"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0054"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0050"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0057"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0053"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0055"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0051"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0049"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0034"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0001"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0005"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0009"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0043"
    )
}

pub(crate) fn is_generated_intrinsic_compatibility_path(path: &str) -> bool {
    matches!(
        path,
        "cuda_device::warp::active_mask"
            | "cuda_device::warp::all_sync"
            | "cuda_device::warp::any_sync"
            | "cuda_device::warp::ballot_sync"
            | "cuda_device::thread::blockDim_x"
            | "cuda_device::blockDim_x"
            | "cuda_device::thread::blockDim_y"
            | "cuda_device::blockDim_y"
            | "cuda_device::thread::blockDim_z"
            | "cuda_device::blockDim_z"
            | "cuda_device::thread::blockIdx_x"
            | "cuda_device::blockIdx_x"
            | "cuda_device::thread::blockIdx_y"
            | "cuda_device::blockIdx_y"
            | "cuda_device::thread::blockIdx_z"
            | "cuda_device::blockIdx_z"
            | "cuda_device::dotprod::dp2a_s32"
            | "cuda_device::dotprod::dp2a_u32"
            | "cuda_device::dotprod::dp4a_s32"
            | "cuda_device::dotprod::dp4a_u32"
            | "cuda_device::thread::gridDim_x"
            | "cuda_device::gridDim_x"
            | "cuda_device::thread::gridDim_y"
            | "cuda_device::gridDim_y"
            | "cuda_device::thread::gridDim_z"
            | "cuda_device::gridDim_z"
            | "cuda_device::warp::lane_id"
            | "cuda_device::warp::lanemask_eq"
            | "cuda_device::warp::lanemask_ge"
            | "cuda_device::warp::lanemask_gt"
            | "cuda_device::warp::lanemask_le"
            | "cuda_device::warp::lanemask_lt"
            | "cuda_device::wmma::ldmatrix_x1"
            | "cuda_device::wmma::ldmatrix_x1_trans"
            | "cuda_device::wmma::ldmatrix_x2"
            | "cuda_device::wmma::ldmatrix_x2_trans"
            | "cuda_device::wmma::ldmatrix_x4"
            | "cuda_device::wmma::ldmatrix_x4_trans"
            | "cuda_device::warp::match_all_i64_sync"
            | "cuda_device::warp::match_all_sync"
            | "cuda_device::warp::match_any_i64_sync"
            | "cuda_device::warp::match_any_sync"
            | "cuda_device::atomic::atom_add_bf16x2"
            | "cuda_device::atomic::atom_add_f16x2"
            | "cuda_device::warp::redux_sync_add"
            | "cuda_device::warp::redux_sync_and"
            | "cuda_device::warp::redux_sync_max_i32"
            | "cuda_device::warp::redux_sync_max_u32"
            | "cuda_device::warp::redux_sync_min_i32"
            | "cuda_device::warp::redux_sync_min_u32"
            | "cuda_device::warp::redux_sync_or"
            | "cuda_device::warp::redux_sync_xor"
            | "cuda_device::warp::shuffle_down_f32_sync"
            | "cuda_device::warp::shuffle_down_sync"
            | "cuda_device::warp::shuffle_f32_sync"
            | "cuda_device::warp::shuffle_sync"
            | "cuda_device::warp::shuffle_up_f32_sync"
            | "cuda_device::warp::shuffle_up_sync"
            | "cuda_device::warp::shuffle_xor_f32_sync"
            | "cuda_device::warp::shuffle_xor_sync"
            | "cuda_device::warp::sync_mask"
            | "cuda_device::thread::sync_threads"
            | "cuda_device::sync_threads"
            | "cuda_device::thread::threadIdx_x"
            | "cuda_device::threadIdx_x"
            | "cuda_device::thread::threadIdx_y"
            | "cuda_device::threadIdx_y"
            | "cuda_device::thread::threadIdx_z"
            | "cuda_device::threadIdx_z"
    )
}

pub(crate) fn is_generated_intrinsic_placeholder(crate_name: &str, path: &str) -> bool {
    if is_generated_intrinsic_crate(crate_name) {
        is_generated_intrinsic_canonical_path(path)
    } else if matches!(crate_name, "cuda_device" | "cuda-device") {
        is_generated_intrinsic_compatibility_path(path)
    } else {
        false
    }
}
