/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 15/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1219fbbe867b025fd75783d0b1209c3759a9c92ee1f7c338631490458457fa58.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated collector predicates for intrinsic placeholder functions.

pub(crate) const GENERATED_INTRINSIC_ABI: u32 = 1;
pub(crate) const GENERATED_INTRINSIC_ABI_NAMESPACE: &str = "__cuda_oxide_intrinsic_abi_v1";
pub(crate) const GENERATED_INTRINSIC_CRATES: &[&str] = &["cuda_intrinsics", "cuda-intrinsics"];

pub(crate) const GENERATED_INTRINSIC_CANONICAL_PATHS: &[&str] = &[
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0070",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0080",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0044",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0064",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0074",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0040",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0041",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0042",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0003",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0007",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0011",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0002",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0006",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0010",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0090",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0086",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0088",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0091",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0087",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0089",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0092",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0093",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0094",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0095",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0096",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0081",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0071",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0084",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0083",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0085",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0082",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0032",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0033",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0030",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0031",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0062",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0072",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0063",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0073",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0004",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0008",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0012",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0016",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0037",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0038",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0039",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0036",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0035",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0025",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0026",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0027",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0028",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0013",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0029",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0048",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0047",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0046",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0045",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0068",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0078",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0098",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0097",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0100",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0099",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0067",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0077",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0066",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0076",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0069",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0079",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0015",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0014",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0017",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0022",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0021",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0020",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0019",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0018",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0023",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0024",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0056",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0052",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0060",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0054",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0050",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0058",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0057",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0053",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0061",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0055",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0051",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0059",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0065",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0075",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0049",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0034",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0001",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0005",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0009",
    "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0043",
];

pub(crate) const GENERATED_INTRINSIC_PUBLIC_PATHS: &[&str] = &[
    "cuda_intrinsics::bf16x2::abs_bf16x2",
    "cuda_intrinsics::f16x2::abs_f16x2",
    "cuda_intrinsics::warp::active_mask",
    "cuda_intrinsics::bf16x2::add_bf16x2",
    "cuda_intrinsics::f16x2::add_f16x2",
    "cuda_intrinsics::warp::all_sync",
    "cuda_intrinsics::warp::any_sync",
    "cuda_intrinsics::warp::ballot_sync",
    "cuda_intrinsics::sreg::block_dim_x",
    "cuda_intrinsics::sreg::block_dim_y",
    "cuda_intrinsics::sreg::block_dim_z",
    "cuda_intrinsics::sreg::block_idx_x",
    "cuda_intrinsics::sreg::block_idx_y",
    "cuda_intrinsics::sreg::block_idx_z",
    "cuda_intrinsics::async_copy::cp_async_ca_16",
    "cuda_intrinsics::async_copy::cp_async_ca_4",
    "cuda_intrinsics::async_copy::cp_async_ca_8",
    "cuda_intrinsics::async_copy::cp_async_ca_zfill_16",
    "cuda_intrinsics::async_copy::cp_async_ca_zfill_4",
    "cuda_intrinsics::async_copy::cp_async_ca_zfill_8",
    "cuda_intrinsics::async_copy::cp_async_cg_16",
    "cuda_intrinsics::async_copy::cp_async_cg_zfill_16",
    "cuda_intrinsics::async_copy::cp_async_commit_group",
    "cuda_intrinsics::async_copy::cp_async_wait_all",
    "cuda_intrinsics::async_copy::cp_async_wait_group",
    "cuda_intrinsics::convert::cvt_f16x2_f32",
    "cuda_intrinsics::convert::cvt_f32x2_bf16x2",
    "cuda_intrinsics::convert::cvt_rn_relu_bf16x2_f32",
    "cuda_intrinsics::convert::cvt_rn_relu_f16x2_f32",
    "cuda_intrinsics::convert::cvt_rz_bf16x2_f32",
    "cuda_intrinsics::convert::cvt_rz_f16x2_f32",
    "cuda_intrinsics::dotprod::dp2a_s32",
    "cuda_intrinsics::dotprod::dp2a_u32",
    "cuda_intrinsics::dotprod::dp4a_s32",
    "cuda_intrinsics::dotprod::dp4a_u32",
    "cuda_intrinsics::bf16x2::fma_bf16x2",
    "cuda_intrinsics::f16x2::fma_f16x2",
    "cuda_intrinsics::bf16x2::fma_relu_bf16x2",
    "cuda_intrinsics::f16x2::fma_relu_f16x2",
    "cuda_intrinsics::sreg::grid_dim_x",
    "cuda_intrinsics::sreg::grid_dim_y",
    "cuda_intrinsics::sreg::grid_dim_z",
    "cuda_intrinsics::sreg::lane_id",
    "cuda_intrinsics::sreg::lanemask_eq",
    "cuda_intrinsics::sreg::lanemask_ge",
    "cuda_intrinsics::sreg::lanemask_gt",
    "cuda_intrinsics::sreg::lanemask_le",
    "cuda_intrinsics::sreg::lanemask_lt",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x1_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x1_trans_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x2_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x2_trans_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x4_b16",
    "cuda_intrinsics::matrix::ldmatrix_m8n8_x4_trans_b16",
    "cuda_intrinsics::warp::match_all_i64_sync",
    "cuda_intrinsics::warp::match_all_sync",
    "cuda_intrinsics::warp::match_any_i64_sync",
    "cuda_intrinsics::warp::match_any_sync",
    "cuda_intrinsics::bf16x2::max_bf16x2",
    "cuda_intrinsics::f16x2::max_f16x2",
    "cuda_intrinsics::barrier::mbarrier_arrive",
    "cuda_intrinsics::barrier::mbarrier_init",
    "cuda_intrinsics::barrier::mbarrier_inval",
    "cuda_intrinsics::barrier::mbarrier_test_wait",
    "cuda_intrinsics::bf16x2::min_bf16x2",
    "cuda_intrinsics::f16x2::min_f16x2",
    "cuda_intrinsics::bf16x2::mul_bf16x2",
    "cuda_intrinsics::f16x2::mul_f16x2",
    "cuda_intrinsics::bf16x2::neg_bf16x2",
    "cuda_intrinsics::f16x2::neg_f16x2",
    "cuda_intrinsics::atomic::atom_add_bf16x2",
    "cuda_intrinsics::atomic::atom_add_f16x2",
    "cuda_intrinsics::warp::redux_sync_add",
    "cuda_intrinsics::warp::redux_sync_and",
    "cuda_intrinsics::warp::redux_sync_max_i32",
    "cuda_intrinsics::warp::redux_sync_max_u32",
    "cuda_intrinsics::warp::redux_sync_min_i32",
    "cuda_intrinsics::warp::redux_sync_min_u32",
    "cuda_intrinsics::warp::redux_sync_or",
    "cuda_intrinsics::warp::redux_sync_xor",
    "cuda_intrinsics::warp::shuffle_down_f32_sync",
    "cuda_intrinsics::warp::shuffle_down_sync",
    "cuda_intrinsics::warp::shuffle_down_u64_sync",
    "cuda_intrinsics::warp::shuffle_f32_sync",
    "cuda_intrinsics::warp::shuffle_sync",
    "cuda_intrinsics::warp::shuffle_u64_sync",
    "cuda_intrinsics::warp::shuffle_up_f32_sync",
    "cuda_intrinsics::warp::shuffle_up_sync",
    "cuda_intrinsics::warp::shuffle_up_u64_sync",
    "cuda_intrinsics::warp::shuffle_xor_f32_sync",
    "cuda_intrinsics::warp::shuffle_xor_sync",
    "cuda_intrinsics::warp::shuffle_xor_u64_sync",
    "cuda_intrinsics::bf16x2::sub_bf16x2",
    "cuda_intrinsics::f16x2::sub_f16x2",
    "cuda_intrinsics::warp::sync_mask",
    "cuda_intrinsics::thread::sync_threads",
    "cuda_intrinsics::sreg::thread_idx_x",
    "cuda_intrinsics::sreg::thread_idx_y",
    "cuda_intrinsics::sreg::thread_idx_z",
    "cuda_intrinsics::warp::uni_sync",
];

pub(crate) fn is_generated_intrinsic_crate(crate_name: &str) -> bool {
    GENERATED_INTRINSIC_CRATES.contains(&crate_name)
}

pub(crate) fn is_generated_intrinsic_canonical_path(path: &str) -> bool {
    matches!(
        path,
        "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0070"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0080"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0044"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0064"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0074"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0040"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0041"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0042"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0003"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0007"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0011"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0002"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0006"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0010"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0090"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0086"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0088"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0091"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0087"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0089"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0092"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0093"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0094"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0095"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0096"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0081"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0071"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0084"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0083"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0085"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0082"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0032"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0033"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0030"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0031"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0062"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0072"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0063"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0073"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0004"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0008"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0012"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0016"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0037"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0038"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0039"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0036"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0035"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0025"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0026"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0027"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0028"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0013"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0029"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0048"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0047"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0046"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0045"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0068"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0078"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0098"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0097"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0100"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0099"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0067"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0077"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0066"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0076"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0069"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0079"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0015"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0014"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0017"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0022"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0021"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0020"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0019"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0018"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0023"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0024"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0056"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0052"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0060"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0054"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0050"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0058"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0057"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0053"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0061"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0055"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0051"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0059"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0065"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0075"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0049"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0034"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0001"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0005"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0009"
            | "cuda_intrinsics::__cuda_oxide_intrinsic_abi_v1::i0043"
    )
}

pub(crate) fn is_generated_intrinsic_compatibility_path(path: &str) -> bool {
    matches!(
        path,
        "cuda_device::bf16x2::abs_bf16x2"
            | "cuda_device::f16x2::abs_f16x2"
            | "cuda_device::warp::active_mask"
            | "cuda_device::bf16x2::add_bf16x2"
            | "cuda_device::f16x2::add_f16x2"
            | "cuda_device::warp::all_sync"
            | "cuda_device::warp::any_sync"
            | "cuda_device::warp::ballot_sync"
            | "cuda_device::thread::blockDim_x"
            | "cuda_device::blockDim_x"
            | "cuda_device::thread::blockDim_y"
            | "cuda_device::blockDim_y"
            | "cuda_device::thread::blockDim_z"
            | "cuda_device::blockDim_z"
            | "cuda_device::thread::blockIdx_x"
            | "cuda_device::blockIdx_x"
            | "cuda_device::thread::blockIdx_y"
            | "cuda_device::blockIdx_y"
            | "cuda_device::thread::blockIdx_z"
            | "cuda_device::blockIdx_z"
            | "cuda_device::async_copy::cp_async_ca_16"
            | "cuda_device::async_copy::cp_async_ca_4"
            | "cuda_device::async_copy::cp_async_ca_8"
            | "cuda_device::async_copy::cp_async_ca_zfill_16"
            | "cuda_device::async_copy::cp_async_ca_zfill_4"
            | "cuda_device::async_copy::cp_async_ca_zfill_8"
            | "cuda_device::async_copy::cp_async_cg_16"
            | "cuda_device::async_copy::cp_async_cg_zfill_16"
            | "cuda_device::async_copy::cp_async_commit_group"
            | "cuda_device::async_copy::cp_async_wait_all"
            | "cuda_device::async_copy::cp_async_wait_group"
            | "cuda_device::convert::cvt_f16x2_f32"
            | "cuda_device::tcgen05::cvt_f32x2_bf16x2"
            | "cuda_device::convert::cvt_rn_relu_bf16x2_f32"
            | "cuda_device::convert::cvt_rn_relu_f16x2_f32"
            | "cuda_device::convert::cvt_rz_bf16x2_f32"
            | "cuda_device::convert::cvt_rz_f16x2_f32"
            | "cuda_device::dotprod::dp2a_s32"
            | "cuda_device::dotprod::dp2a_u32"
            | "cuda_device::dotprod::dp4a_s32"
            | "cuda_device::dotprod::dp4a_u32"
            | "cuda_device::bf16x2::fma_bf16x2"
            | "cuda_device::f16x2::fma_f16x2"
            | "cuda_device::bf16x2::fma_relu_bf16x2"
            | "cuda_device::f16x2::fma_relu_f16x2"
            | "cuda_device::thread::gridDim_x"
            | "cuda_device::gridDim_x"
            | "cuda_device::thread::gridDim_y"
            | "cuda_device::gridDim_y"
            | "cuda_device::thread::gridDim_z"
            | "cuda_device::gridDim_z"
            | "cuda_device::warp::lane_id"
            | "cuda_device::warp::lanemask_eq"
            | "cuda_device::warp::lanemask_ge"
            | "cuda_device::warp::lanemask_gt"
            | "cuda_device::warp::lanemask_le"
            | "cuda_device::warp::lanemask_lt"
            | "cuda_device::wmma::ldmatrix_x1"
            | "cuda_device::wmma::ldmatrix_x1_trans"
            | "cuda_device::wmma::ldmatrix_x2"
            | "cuda_device::wmma::ldmatrix_x2_trans"
            | "cuda_device::wmma::ldmatrix_x4"
            | "cuda_device::wmma::ldmatrix_x4_trans"
            | "cuda_device::warp::match_all_i64_sync"
            | "cuda_device::warp::match_all_sync"
            | "cuda_device::warp::match_any_i64_sync"
            | "cuda_device::warp::match_any_sync"
            | "cuda_device::bf16x2::max_bf16x2"
            | "cuda_device::f16x2::max_f16x2"
            | "cuda_device::barrier::mbarrier_arrive"
            | "cuda_device::barrier::mbarrier_init"
            | "cuda_device::barrier::mbarrier_inval"
            | "cuda_device::barrier::mbarrier_test_wait"
            | "cuda_device::bf16x2::min_bf16x2"
            | "cuda_device::f16x2::min_f16x2"
            | "cuda_device::bf16x2::mul_bf16x2"
            | "cuda_device::f16x2::mul_f16x2"
            | "cuda_device::bf16x2::neg_bf16x2"
            | "cuda_device::f16x2::neg_f16x2"
            | "cuda_device::atomic::atom_add_bf16x2"
            | "cuda_device::atomic::atom_add_f16x2"
            | "cuda_device::warp::redux_sync_add"
            | "cuda_device::warp::redux_sync_and"
            | "cuda_device::warp::redux_sync_max_i32"
            | "cuda_device::warp::redux_sync_max_u32"
            | "cuda_device::warp::redux_sync_min_i32"
            | "cuda_device::warp::redux_sync_min_u32"
            | "cuda_device::warp::redux_sync_or"
            | "cuda_device::warp::redux_sync_xor"
            | "cuda_device::warp::shuffle_down_f32_sync"
            | "cuda_device::warp::shuffle_down_sync"
            | "cuda_device::warp::shuffle_down_u64_sync"
            | "cuda_device::warp::shuffle_f32_sync"
            | "cuda_device::warp::shuffle_sync"
            | "cuda_device::warp::shuffle_u64_sync"
            | "cuda_device::warp::shuffle_up_f32_sync"
            | "cuda_device::warp::shuffle_up_sync"
            | "cuda_device::warp::shuffle_up_u64_sync"
            | "cuda_device::warp::shuffle_xor_f32_sync"
            | "cuda_device::warp::shuffle_xor_sync"
            | "cuda_device::warp::shuffle_xor_u64_sync"
            | "cuda_device::bf16x2::sub_bf16x2"
            | "cuda_device::f16x2::sub_f16x2"
            | "cuda_device::warp::sync_mask"
            | "cuda_device::thread::sync_threads"
            | "cuda_device::sync_threads"
            | "cuda_device::thread::threadIdx_x"
            | "cuda_device::threadIdx_x"
            | "cuda_device::thread::threadIdx_y"
            | "cuda_device::threadIdx_y"
            | "cuda_device::thread::threadIdx_z"
            | "cuda_device::threadIdx_z"
    )
}

pub(crate) fn is_generated_intrinsic_placeholder(crate_name: &str, path: &str) -> bool {
    if is_generated_intrinsic_crate(crate_name) {
        is_generated_intrinsic_canonical_path(path)
    } else if matches!(crate_name, "cuda_device" | "cuda-device") {
        is_generated_intrinsic_compatibility_path(path)
    } else {
        false
    }
}
