[package]
name = "warp_sums"
version = "0.1.0"
edition = "2024"
authors = ["NVIDIA Corporation"]
license = "Apache-2.0"

[workspace]

[dependencies]
cuda-core = { git = "https://github.com/NVlabs/cutile-rs", branch = "feat/cuda-oxide-host-support" }
cuda-device = { path = "../../../cuda-device" }
cuda-host = { path = "../../../cuda-host" }
