/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 13/0.1.0; intrinsic ABI: v1; catalog SHA-256: 4328ffc4bd5d5ae95dfaf6ee0e73806ce1b93ca31b54d405ab1ac38f61b9edcb.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated conversion interfaces for admitted CUDA intrinsic families.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    atomic::convert_packed_atom_add,
    common::{call_intrinsic, create_i32_const, inline_asm_convergent},
    dotprod::convert_generated_dot_product,
    ldmatrix::convert_generated_ldmatrix,
    packed::{convert_generated_packed_alu, convert_generated_packed_f32x2},
    warp::{
        convert_active_mask, convert_bar_warp_sync, convert_match_all, convert_match_any,
        convert_redux, convert_shuffle_f32, convert_shuffle_i32, convert_shuffle_i64, convert_vote,
    },
};
use crate::{IntrinsicBackend, context};
use dialect_nvvm::ops::{
    AbsBf16x2Op, AbsF16x2Op, ActiveMaskOp, AddBf16x2Op, AddF16x2Op, BarWarpSyncOp, Barrier0Op,
    CvtF16x2F32Op, CvtF32x2Bf16x2Op, CvtRnReluBf16x2F32Op, CvtRnReluF16x2F32Op, CvtRzBf16x2F32Op,
    CvtRzF16x2F32Op, Dp2aS32Op, Dp2aU32Op, Dp4aS32Op, Dp4aU32Op, FmaBf16x2Op, FmaF16x2Op,
    FmaReluBf16x2Op, FmaReluF16x2Op, LdmatrixElementAttr, LdmatrixLayoutAttr,
    LdmatrixMultiplicityAttr, LdmatrixOp, LdmatrixShapeAttr, LdmatrixStateSpaceAttr,
    MatchAllSyncI32Op, MatchAllSyncI64Op, MatchAnySyncI32Op, MatchAnySyncI64Op, MaxBf16x2Op,
    MaxF16x2Op, MinBf16x2Op, MinF16x2Op, MulBf16x2Op, MulF16x2Op, NegBf16x2Op, NegF16x2Op,
    PackedAtomicAddOp, PackedAtomicAtomicityAttr, PackedAtomicFormatAttr, PackedAtomicOrderingAttr,
    PackedAtomicRoundingAttr, PackedAtomicScopeAttr, PackedAtomicStateSpaceAttr,
    PackedAtomicSubnormalAttr, ReadPtxSregCtaidXOp, ReadPtxSregCtaidYOp, ReadPtxSregCtaidZOp,
    ReadPtxSregLaneIdOp, ReadPtxSregLanemaskEqOp, ReadPtxSregLanemaskGeOp, ReadPtxSregLanemaskGtOp,
    ReadPtxSregLanemaskLeOp, ReadPtxSregLanemaskLtOp, ReadPtxSregNctaidXOp, ReadPtxSregNctaidYOp,
    ReadPtxSregNctaidZOp, ReadPtxSregNtidXOp, ReadPtxSregNtidYOp, ReadPtxSregNtidZOp,
    ReadPtxSregTidXOp, ReadPtxSregTidYOp, ReadPtxSregTidZOp, ReduxSyncAddOp, ReduxSyncAndOp,
    ReduxSyncMaxOp, ReduxSyncMinOp, ReduxSyncOrOp, ReduxSyncUmaxOp, ReduxSyncUminOp,
    ReduxSyncXorOp, ShflSyncBflyF32Op, ShflSyncBflyI32Op, ShflSyncBflyI64Op, ShflSyncDownF32Op,
    ShflSyncDownI32Op, ShflSyncDownI64Op, ShflSyncIdxF32Op, ShflSyncIdxI32Op, ShflSyncIdxI64Op,
    ShflSyncUpF32Op, ShflSyncUpI32Op, ShflSyncUpI64Op, SubBf16x2Op, SubF16x2Op, VoteSyncAllOp,
    VoteSyncAnyOp, VoteSyncBallotOp, VoteSyncUniOp,
};
use llvm_export::types as llvm_types;
use pliron::{
    builtin::types::{IntegerType, Signedness},
    context::{Context, Ptr},
    derive::op_interface_impl,
    irbuild::{
        dialect_conversion::{DialectConversionRewriter, OperandsInfo},
        rewriter::Rewriter,
    },
    op::Op,
    operation::Operation,
    result::Result,
};

use pliron::location::Located;

fn convert_zero_operand_scalar_direct(
    ctx: &mut Context,
    rewriter: &mut DialectConversionRewriter,
    op: Ptr<Operation>,
    width: u32,
    intrinsic_name: &str,
) -> Result<()> {
    let result_ty = IntegerType::get(ctx, width, Signedness::Signless);
    let function_ty = llvm_types::FuncType::get(ctx, result_ty.into(), vec![], false);
    let call = call_intrinsic(ctx, rewriter, op, intrinsic_name, function_ty, vec![])?;
    rewriter.replace_operation(ctx, op, call);
    Ok(())
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLaneIdOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_laneid",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskEqOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_eq",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskGeOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_ge",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskGtOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_gt",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskLeOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_le",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskLtOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_lt",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ActiveMaskOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        match context::lowering_options(ctx).intrinsic_backend {
            IntrinsicBackend::LlvmNvptx => convert_active_mask(ctx, rewriter, op, operands_info),
            IntrinsicBackend::LibNvvm => {
                let i32_ty = IntegerType::get(ctx, 32, Signedness::Signless);
                let inline_asm = inline_asm_convergent(
                    ctx,
                    rewriter,
                    i32_ty.into(),
                    vec![],
                    "activemask.b32 $0;",
                    "=r,~{memory}",
                );
                rewriter.replace_operation(ctx, op, inline_asm);
                Ok(())
            }
        }
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for LdmatrixOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let recipe = {
            let shape = self.get_attr_nvvm_ldmatrix_shape(ctx);
            let multiplicity = self.get_attr_nvvm_ldmatrix_multiplicity(ctx);
            let layout = self.get_attr_nvvm_ldmatrix_layout(ctx);
            let element = self.get_attr_nvvm_ldmatrix_element(ctx);
            let state_space = self.get_attr_nvvm_ldmatrix_state_space(ctx);
            match (
                shape.as_deref(),
                multiplicity.as_deref(),
                layout.as_deref(),
                element.as_deref(),
                state_space.as_deref(),
            ) {
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X1),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (1, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x1_b16_p3"),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X1),
                    Some(&LdmatrixLayoutAttr::Transposed),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (
                    1,
                    true,
                    "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x1_trans_b16_p3",
                ),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X2),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (2, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x2_b16_p3"),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X2),
                    Some(&LdmatrixLayoutAttr::Transposed),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (
                    2,
                    true,
                    "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x2_trans_b16_p3",
                ),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X4),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (4, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x4_b16_p3"),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X4),
                    Some(&LdmatrixLayoutAttr::Transposed),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (
                    4,
                    true,
                    "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x4_trans_b16_p3",
                ),
                _ => {
                    return pliron::input_err!(
                        self.get_operation().deref(ctx).loc(),
                        "nvvm.ldmatrix variant has no generated lowering recipe",
                    );
                }
            }
        };
        convert_generated_ldmatrix(
            ctx,
            rewriter,
            self.get_operation(),
            recipe.0,
            recipe.1,
            recipe.2,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for PackedAtomicAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let format = self.get_attr_nvvm_packed_atomic_format(ctx);
        let state_space = self.get_attr_nvvm_packed_atomic_state_space(ctx);
        let ordering = self.get_attr_nvvm_packed_atomic_ordering(ctx);
        let scope = self.get_attr_nvvm_packed_atomic_scope(ctx);
        let rounding = self.get_attr_nvvm_packed_atomic_rounding(ctx);
        let subnormal = self.get_attr_nvvm_packed_atomic_subnormal(ctx);
        let atomicity = self.get_attr_nvvm_packed_atomic_atomicity(ctx);
        let ptx_type = match (
            format.as_deref(),
            state_space.as_deref(),
            ordering.as_deref(),
            scope.as_deref(),
            rounding.as_deref(),
            subnormal.as_deref(),
            atomicity.as_deref(),
        ) {
            (
                Some(&PackedAtomicFormatAttr::F16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "f16x2",
            (
                Some(&PackedAtomicFormatAttr::Bf16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "bf16x2",
            _ => {
                return pliron::input_err!(
                    self.get_operation().deref(ctx).loc(),
                    "nvvm.packed_atomic_add attributes have no generated lowering recipe",
                );
            }
        };
        drop((
            format,
            state_space,
            ordering,
            scope,
            rounding,
            subnormal,
            atomicity,
        ));
        convert_packed_atom_add(ctx, rewriter, self.get_operation(), ptx_type)
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_add",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncAndOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_and",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncMaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_max",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncUmaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_umax",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncMinOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_min",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncUminOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_umin",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncOrOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_or",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncXorOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_xor",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncAllOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_all_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncAnyOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_any_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncBallotOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_ballot_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncUniOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_uni_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAllSyncI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 64, Signedness::Signless);
        convert_match_all(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_all_sync_i64p",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAllSyncI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        convert_match_all(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_all_sync_i32p",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAnySyncI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 64, Signedness::Signless);
        convert_match_any(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_any_sync_i64",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAnySyncI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        convert_match_any(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_any_sync_i32",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for BarWarpSyncOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_bar_warp_sync(ctx, rewriter, self.get_operation(), operands_info)
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncDownF32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_f32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_down_f32",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncDownI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_down_i32",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncDownI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i64(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "down",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncIdxF32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_f32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_idx_f32",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncIdxI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_idx_i32",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncIdxI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i64(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "idx",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncUpF32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_f32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_up_f32",
            0,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncUpI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_up_i32",
            0,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncUpI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i64(ctx, rewriter, self.get_operation(), operands_info, "up", 0)
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncBflyF32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_f32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_bfly_f32",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncBflyI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i32(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_shfl_sync_bfly_i32",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ShflSyncBflyI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_shuffle_i64(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "bfly",
            31,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for AbsBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "abs.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for AbsF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "abs.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for AddBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "add.rn.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for AddF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "add.rn.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FmaBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "fma.rn.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FmaF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "fma.rn.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FmaReluBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "fma.rn.relu.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FmaReluF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "fma.rn.relu.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MaxBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "max.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MaxF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "max.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MinBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "min.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MinF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "min.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MulBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "mul.rn.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MulF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "mul.rn.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for NegBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "neg.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for NegF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "neg.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for SubBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "sub.rn.bf16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for SubF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_alu(ctx, rewriter, self.get_operation(), "sub.rn.f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtF16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(ctx, rewriter, self.get_operation(), "cvt.rn.f16x2.f32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtF32x2Bf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(ctx, rewriter, self.get_operation(), "cvt.rn.bf16x2.f32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnReluBf16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.relu.bf16x2.f32",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnReluF16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(ctx, rewriter, self.get_operation(), "cvt.rn.relu.f16x2.f32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRzBf16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(ctx, rewriter, self.get_operation(), "cvt.rz.bf16x2.f32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRzF16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(ctx, rewriter, self.get_operation(), "cvt.rz.f16x2.f32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp2aS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp2a_s_s",
            "dp2a.lo.s32.s32 $0, $1, $2, $3;",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp2aU32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp2a_u_u",
            "dp2a.lo.u32.u32 $0, $1, $2, $3;",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp4aS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp4a_s_s",
            "dp4a.s32.s32 $0, $1, $2, $3;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp4aU32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp4a_u_u",
            "dp4a.u32.u32 $0, $1, $2, $3;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Barrier0Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let void_ty = llvm_types::VoidType::get(ctx);
        match context::lowering_options(ctx).intrinsic_backend {
            IntrinsicBackend::LlvmNvptx => {
                let i32_ty = IntegerType::get(ctx, 32, Signedness::Signless);
                let barrier_id = create_i32_const(ctx, rewriter, 0);
                let function_ty =
                    llvm_types::FuncType::get(ctx, void_ty.into(), vec![i32_ty.into()], false);
                call_intrinsic(
                    ctx,
                    rewriter,
                    op,
                    "llvm_nvvm_barrier_cta_sync_aligned_all",
                    function_ty,
                    vec![barrier_id],
                )?;
            }
            IntrinsicBackend::LibNvvm => {
                inline_asm_convergent(
                    ctx,
                    rewriter,
                    void_ty.into(),
                    vec![],
                    "bar.sync 0;",
                    "~{memory}",
                );
            }
        }
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}
