/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 6/0.1.0; intrinsic ABI: v1; catalog SHA-256: 51664f8e3ecc850ca5c119d4293806446bc623b61e7979e711e7f17fe5d1fbb8.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated conversion interfaces for admitted CUDA intrinsic families.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    atomic::convert_packed_atom_add,
    common::{call_intrinsic, create_i32_const, inline_asm_convergent},
    dotprod::convert_generated_dot_product,
    ldmatrix::convert_generated_ldmatrix,
    warp::{convert_redux, convert_vote},
};
use crate::{IntrinsicBackend, context};
use dialect_nvvm::ops::{
    Barrier0Op, Dp2aS32Op, Dp2aU32Op, Dp4aS32Op, Dp4aU32Op, LdmatrixElementAttr,
    LdmatrixLayoutAttr, LdmatrixMultiplicityAttr, LdmatrixOp, LdmatrixShapeAttr,
    LdmatrixStateSpaceAttr, PackedAtomicAddOp, PackedAtomicAtomicityAttr, PackedAtomicFormatAttr,
    PackedAtomicOrderingAttr, PackedAtomicRoundingAttr, PackedAtomicScopeAttr,
    PackedAtomicStateSpaceAttr, PackedAtomicSubnormalAttr, ReadPtxSregCtaidXOp,
    ReadPtxSregCtaidYOp, ReadPtxSregCtaidZOp, ReadPtxSregLaneIdOp, ReadPtxSregLanemaskEqOp,
    ReadPtxSregLanemaskGeOp, ReadPtxSregLanemaskGtOp, ReadPtxSregLanemaskLeOp,
    ReadPtxSregLanemaskLtOp, ReadPtxSregNctaidXOp, ReadPtxSregNctaidYOp, ReadPtxSregNctaidZOp,
    ReadPtxSregNtidXOp, ReadPtxSregNtidYOp, ReadPtxSregNtidZOp, ReadPtxSregTidXOp,
    ReadPtxSregTidYOp, ReadPtxSregTidZOp, ReduxSyncAddOp, ReduxSyncAndOp, ReduxSyncMaxOp,
    ReduxSyncMinOp, ReduxSyncOrOp, ReduxSyncUmaxOp, ReduxSyncUminOp, ReduxSyncXorOp, VoteSyncAllOp,
    VoteSyncAnyOp, VoteSyncBallotOp, VoteSyncUniOp,
};
use llvm_export::types as llvm_types;
use pliron::{
    builtin::types::{IntegerType, Signedness},
    context::{Context, Ptr},
    derive::op_interface_impl,
    irbuild::{
        dialect_conversion::{DialectConversionRewriter, OperandsInfo},
        rewriter::Rewriter,
    },
    op::Op,
    operation::Operation,
    result::Result,
};

use pliron::location::Located;

fn convert_zero_operand_scalar_direct(
    ctx: &mut Context,
    rewriter: &mut DialectConversionRewriter,
    op: Ptr<Operation>,
    width: u32,
    intrinsic_name: &str,
) -> Result<()> {
    let result_ty = IntegerType::get(ctx, width, Signedness::Signless);
    let function_ty = llvm_types::FuncType::get(ctx, result_ty.into(), vec![], false);
    let call = call_intrinsic(ctx, rewriter, op, intrinsic_name, function_ty, vec![])?;
    rewriter.replace_operation(ctx, op, call);
    Ok(())
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLaneIdOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_laneid",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskEqOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_eq",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskGeOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_ge",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskGtOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_gt",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskLeOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_le",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregLanemaskLtOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_lanemask_lt",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for LdmatrixOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let recipe = {
            let shape = self.get_attr_nvvm_ldmatrix_shape(ctx);
            let multiplicity = self.get_attr_nvvm_ldmatrix_multiplicity(ctx);
            let layout = self.get_attr_nvvm_ldmatrix_layout(ctx);
            let element = self.get_attr_nvvm_ldmatrix_element(ctx);
            let state_space = self.get_attr_nvvm_ldmatrix_state_space(ctx);
            match (
                shape.as_deref(),
                multiplicity.as_deref(),
                layout.as_deref(),
                element.as_deref(),
                state_space.as_deref(),
            ) {
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X1),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (1, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x1_b16_p3"),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X1),
                    Some(&LdmatrixLayoutAttr::Transposed),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (
                    1,
                    true,
                    "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x1_trans_b16_p3",
                ),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X2),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (2, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x2_b16_p3"),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X2),
                    Some(&LdmatrixLayoutAttr::Transposed),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (
                    2,
                    true,
                    "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x2_trans_b16_p3",
                ),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X4),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (4, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x4_b16_p3"),
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X4),
                    Some(&LdmatrixLayoutAttr::Transposed),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (
                    4,
                    true,
                    "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x4_trans_b16_p3",
                ),
                _ => {
                    return pliron::input_err!(
                        self.get_operation().deref(ctx).loc(),
                        "nvvm.ldmatrix variant has no generated lowering recipe",
                    );
                }
            }
        };
        convert_generated_ldmatrix(
            ctx,
            rewriter,
            self.get_operation(),
            recipe.0,
            recipe.1,
            recipe.2,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for PackedAtomicAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let format = self.get_attr_nvvm_packed_atomic_format(ctx);
        let state_space = self.get_attr_nvvm_packed_atomic_state_space(ctx);
        let ordering = self.get_attr_nvvm_packed_atomic_ordering(ctx);
        let scope = self.get_attr_nvvm_packed_atomic_scope(ctx);
        let rounding = self.get_attr_nvvm_packed_atomic_rounding(ctx);
        let subnormal = self.get_attr_nvvm_packed_atomic_subnormal(ctx);
        let atomicity = self.get_attr_nvvm_packed_atomic_atomicity(ctx);
        let ptx_type = match (
            format.as_deref(),
            state_space.as_deref(),
            ordering.as_deref(),
            scope.as_deref(),
            rounding.as_deref(),
            subnormal.as_deref(),
            atomicity.as_deref(),
        ) {
            (
                Some(&PackedAtomicFormatAttr::F16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "f16x2",
            (
                Some(&PackedAtomicFormatAttr::Bf16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "bf16x2",
            _ => {
                return pliron::input_err!(
                    self.get_operation().deref(ctx).loc(),
                    "nvvm.packed_atomic_add attributes have no generated lowering recipe",
                );
            }
        };
        drop((
            format,
            state_space,
            ordering,
            scope,
            rounding,
            subnormal,
            atomicity,
        ));
        convert_packed_atom_add(ctx, rewriter, self.get_operation(), ptx_type)
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_add",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncAndOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_and",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncMaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_max",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncUmaxOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_umax",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncMinOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_min",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncUminOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_umin",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncOrOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_or",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReduxSyncXorOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_redux(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_redux_sync_xor",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncAllOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_all_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncAnyOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_any_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncBallotOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_ballot_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for VoteSyncUniOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_vote(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_vote_uni_sync",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp2aS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp2a_s_s",
            "dp2a.lo.s32.s32 $0, $1, $2, $3;",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp2aU32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp2a_u_u",
            "dp2a.lo.u32.u32 $0, $1, $2, $3;",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp4aS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp4a_s_s",
            "dp4a.s32.s32 $0, $1, $2, $3;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp4aU32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp4a_u_u",
            "dp4a.u32.u32 $0, $1, $2, $3;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Barrier0Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let void_ty = llvm_types::VoidType::get(ctx);
        match context::lowering_options(ctx).intrinsic_backend {
            IntrinsicBackend::LlvmNvptx => {
                let i32_ty = IntegerType::get(ctx, 32, Signedness::Signless);
                let barrier_id = create_i32_const(ctx, rewriter, 0);
                let function_ty =
                    llvm_types::FuncType::get(ctx, void_ty.into(), vec![i32_ty.into()], false);
                call_intrinsic(
                    ctx,
                    rewriter,
                    op,
                    "llvm_nvvm_barrier_cta_sync_aligned_all",
                    function_ty,
                    vec![barrier_id],
                )?;
            }
            IntrinsicBackend::LibNvvm => {
                inline_asm_convergent(
                    ctx,
                    rewriter,
                    void_ty.into(),
                    vec![],
                    "bar.sync 0;",
                    "~{memory}",
                );
            }
        }
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}
