/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 4/0.1.0; intrinsic ABI: v1; catalog SHA-256: aebd3ab8344288e3c511fdd6da2072fb46d05ab45ae6559e307e0711f5c64d94.
// LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

//! Generated direct-NVVM, ldmatrix, and packed-atomic conversion interfaces.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    atomic::convert_packed_atom_add, common::call_intrinsic, ldmatrix::convert_generated_ldmatrix,
};
use dialect_nvvm::ops::{
    LdmatrixElementAttr, LdmatrixLayoutAttr, LdmatrixMultiplicityAttr, LdmatrixOp,
    LdmatrixShapeAttr, LdmatrixStateSpaceAttr, PackedAtomicAddOp, PackedAtomicAtomicityAttr,
    PackedAtomicFormatAttr, PackedAtomicOrderingAttr, PackedAtomicRoundingAttr,
    PackedAtomicScopeAttr, PackedAtomicStateSpaceAttr, PackedAtomicSubnormalAttr,
    ReadPtxSregCtaidXOp, ReadPtxSregCtaidYOp, ReadPtxSregCtaidZOp, ReadPtxSregNctaidXOp,
    ReadPtxSregNctaidYOp, ReadPtxSregNctaidZOp, ReadPtxSregNtidXOp, ReadPtxSregNtidYOp,
    ReadPtxSregNtidZOp, ReadPtxSregTidXOp, ReadPtxSregTidYOp, ReadPtxSregTidZOp,
};
use llvm_export::types as llvm_types;
use pliron::{
    builtin::types::{IntegerType, Signedness},
    context::{Context, Ptr},
    derive::op_interface_impl,
    irbuild::{
        dialect_conversion::{DialectConversionRewriter, OperandsInfo},
        rewriter::Rewriter,
    },
    op::Op,
    operation::Operation,
    result::Result,
};

use pliron::location::Located;

fn convert_zero_operand_scalar_direct(
    ctx: &mut Context,
    rewriter: &mut DialectConversionRewriter,
    op: Ptr<Operation>,
    width: u32,
    intrinsic_name: &str,
) -> Result<()> {
    let result_ty = IntegerType::get(ctx, width, Signedness::Signless);
    let function_ty = llvm_types::FuncType::get(ctx, result_ty.into(), vec![], false);
    let call = call_intrinsic(ctx, rewriter, op, intrinsic_name, function_ty, vec![])?;
    rewriter.replace_operation(ctx, op, call);
    Ok(())
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNtidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ntid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregCtaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_ctaid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregNctaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_nctaid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_x",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_y",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ReadPtxSregTidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_zero_operand_scalar_direct(
            ctx,
            rewriter,
            self.get_operation(),
            32,
            "llvm_nvvm_read_ptx_sreg_tid_z",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for LdmatrixOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let recipe = {
            let shape = self.get_attr_nvvm_ldmatrix_shape(ctx);
            let multiplicity = self.get_attr_nvvm_ldmatrix_multiplicity(ctx);
            let layout = self.get_attr_nvvm_ldmatrix_layout(ctx);
            let element = self.get_attr_nvvm_ldmatrix_element(ctx);
            let state_space = self.get_attr_nvvm_ldmatrix_state_space(ctx);
            match (
                shape.as_deref(),
                multiplicity.as_deref(),
                layout.as_deref(),
                element.as_deref(),
                state_space.as_deref(),
            ) {
                (
                    Some(&LdmatrixShapeAttr::M8n8),
                    Some(&LdmatrixMultiplicityAttr::X4),
                    Some(&LdmatrixLayoutAttr::Normal),
                    Some(&LdmatrixElementAttr::B16),
                    Some(&LdmatrixStateSpaceAttr::Shared),
                ) => (4, false, "llvm_nvvm_ldmatrix_sync_aligned_m8n8_x4_b16_p3"),
                _ => {
                    return pliron::input_err!(
                        self.get_operation().deref(ctx).loc(),
                        "nvvm.ldmatrix variant has no generated lowering recipe",
                    );
                }
            }
        };
        convert_generated_ldmatrix(
            ctx,
            rewriter,
            self.get_operation(),
            recipe.0,
            recipe.1,
            recipe.2,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for PackedAtomicAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let format = self.get_attr_nvvm_packed_atomic_format(ctx);
        let state_space = self.get_attr_nvvm_packed_atomic_state_space(ctx);
        let ordering = self.get_attr_nvvm_packed_atomic_ordering(ctx);
        let scope = self.get_attr_nvvm_packed_atomic_scope(ctx);
        let rounding = self.get_attr_nvvm_packed_atomic_rounding(ctx);
        let subnormal = self.get_attr_nvvm_packed_atomic_subnormal(ctx);
        let atomicity = self.get_attr_nvvm_packed_atomic_atomicity(ctx);
        let ptx_type = match (
            format.as_deref(),
            state_space.as_deref(),
            ordering.as_deref(),
            scope.as_deref(),
            rounding.as_deref(),
            subnormal.as_deref(),
            atomicity.as_deref(),
        ) {
            (
                Some(&PackedAtomicFormatAttr::F16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "f16x2",
            (
                Some(&PackedAtomicFormatAttr::Bf16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "bf16x2",
            _ => {
                return pliron::input_err!(
                    self.get_operation().deref(ctx).loc(),
                    "nvvm.packed_atomic_add attributes have no generated lowering recipe",
                );
            }
        };
        drop((
            format,
            state_space,
            ordering,
            scope,
            rounding,
            subnormal,
            atomicity,
        ));
        convert_packed_atom_add(ctx, rewriter, self.get_operation(), ptx_type)
    }
}
